import { neon } from "@neondatabase/serverless";
import { drizzle } from "drizzle-orm/neon-http";
import {
  growthOutreachTargets,
  growthDirectorySubmissions,
} from "./schema";

async function seed() {
  const url = process.env.DATABASE_URL;
  if (!url) throw new Error("DATABASE_URL not set");

  const sql = neon(url);
  const db = drizzle(sql);

  console.log("Seeding outreach targets...");

  const outreachTargets = [
    {
      siteName: "BloggingWizard",
      articleTitle: "10 Best Image Compression Tools 2026",
      articleUrl: "https://bloggingwizard.com/contact",
      contactName: "Adam Connell",
      contactEmail: null,
      contactLinkedin: null,
      status: "to_send",
    },
    {
      siteName: "ThemeIsle",
      articleTitle: "11 Best Online Image Optimizer Tools",
      articleUrl: "https://themeisle.com/contact",
      contactName: "Priya",
      contactEmail: null,
      contactLinkedin: null,
      status: "to_send",
    },
    {
      siteName: "DEV Community",
      articleTitle: "7 Best Image Compressors 2026",
      articleUrl: "https://dev.to/isuatfurkan",
      contactName: "Suat Furkan",
      contactEmail: null,
      contactLinkedin: null,
      status: "to_send",
    },
    {
      siteName: "Aftershoot",
      articleTitle: "8 Best Lossless Compression Tools",
      articleUrl: null,
      contactName: "Team",
      contactEmail: "hello@aftershoot.com",
      contactLinkedin: null,
      status: "to_send",
    },
    {
      siteName: "TinyIMG",
      articleTitle: "15 Best TinyPNG Alternatives",
      articleUrl: "https://tiny-img.com",
      contactName: "Vita Klimaite",
      contactEmail: null,
      contactLinkedin: null,
      status: "to_send",
    },
    {
      siteName: "Aiarty",
      articleTitle: "Top 10 TinyPNG Alternatives",
      articleUrl: "https://aiarty.com",
      contactName: "Brenda Peng",
      contactEmail: null,
      contactLinkedin: null,
      status: "to_send",
    },
    {
      siteName: "ShortPixel",
      articleTitle: "Best PNG Compressor Alternatives",
      articleUrl: null,
      contactName: "Andrei Alba",
      contactEmail: "aalba@shortpixel.com",
      contactLinkedin: null,
      status: "to_send",
    },
    {
      siteName: "IORiver",
      articleTitle: "Best 10 Image Optimization Tools",
      articleUrl: "https://ioriver.io/contact",
      contactName: "Rostyslav",
      contactEmail: null,
      contactLinkedin: null,
      status: "to_send",
    },
    {
      siteName: "DEV Community",
      articleTitle: "11 Free Image Tools for Frontend",
      articleUrl: "https://dev.to/joywinter90",
      contactName: "Joy Winter",
      contactEmail: null,
      contactLinkedin: null,
      status: "to_send",
    },
    {
      siteName: "Shrink.media",
      articleTitle: "20 Best Compression Tools",
      articleUrl: "https://shrink.media",
      contactName: "PixelBin",
      contactEmail: null,
      contactLinkedin: null,
      status: "to_send",
    },
    {
      siteName: "Showit",
      articleTitle: "Best Image Optimization Tools 2025",
      articleUrl: "https://showit.com",
      contactName: "Team",
      contactEmail: null,
      contactLinkedin: null,
      status: "to_send",
    },
    {
      siteName: "Wondershare",
      articleTitle: "7 Best HEIC Converter Online",
      articleUrl: "https://wondershare.com",
      contactName: "Axel Nash",
      contactEmail: null,
      contactLinkedin: null,
      status: "to_send",
    },
    {
      siteName: "Coolmuster",
      articleTitle: "12 Best HEIC to JPG Converter",
      articleUrl: "https://coolmuster.com/contact",
      contactName: "Brandon Wood",
      contactEmail: null,
      contactLinkedin: null,
      status: "to_send",
    },
    {
      siteName: "OPT-IMG",
      articleTitle: "Best Batch Processing Tools 2026",
      articleUrl: "https://opt-img.com",
      contactName: "Team",
      contactEmail: null,
      contactLinkedin: null,
      status: "to_send",
    },
    {
      siteName: "ClippingPathExperts",
      articleTitle: "Best Free Batch Image Resizer",
      articleUrl: null,
      contactName: "Ahmed Efaz",
      contactEmail: "info@clippingpathexperts.com",
      contactLinkedin: null,
      status: "to_send",
    },
    {
      siteName: "WhatSoftware",
      articleTitle: "10 Best Free Batch Image Resizer",
      articleUrl: "https://whatsoftware.com/contact",
      contactName: "HAL9000",
      contactEmail: null,
      contactLinkedin: null,
      status: "to_send",
    },
    {
      siteName: "QuickToolsHQ",
      articleTitle: "Best Free Compression Tools 2025",
      articleUrl: null,
      contactName: "Team",
      contactEmail: "hello@quicktoolshq.com",
      contactLinkedin: null,
      status: "to_send",
    },
    {
      siteName: "Attrock",
      articleTitle: "The Best Image Compression Tools for Your Website",
      articleUrl: "https://attrock.com/blog/best-image-compression-tools/",
      contactName: "Gaurav Sharma",
      contactEmail: "gaurav@attrock.com",
      contactLinkedin: null,
      status: "to_send",
    },
    {
      siteName: "Geekflare",
      articleTitle: "9 Free Image Compression Tools to Boost Website Speed",
      articleUrl: "https://geekflare.com/image-compression-tools/",
      contactName: "Durga Prasad Acharya",
      contactEmail: null,
      contactLinkedin: null,
      status: "to_send",
    },
    {
      siteName: "Kinsta",
      articleTitle: "How To Optimize Images for Web and Performance",
      articleUrl: "https://kinsta.com/blog/optimize-images-for-web/",
      contactName: "Brian Jackson",
      contactEmail: null,
      contactLinkedin: null,
      status: "to_send",
    },
    {
      siteName: "The Admin Bar",
      articleTitle: "The Best Online Image Compression Services Compared",
      articleUrl: "https://theadminbar.com/the-best-online-image-compression-services-compared/",
      contactName: "Kyle Van Deusen",
      contactEmail: null,
      contactLinkedin: null,
      status: "to_send",
    },
    {
      siteName: "WPBeginner",
      articleTitle: "I Tested the 7 Best WordPress Image Compression Plugins",
      articleUrl: "https://www.wpbeginner.com/plugins/best-wordpress-image-compression-plugins-compared/",
      contactName: "Syed Balkhi",
      contactEmail: "support@wpbeginner.com",
      contactLinkedin: null,
      status: "to_send",
    },
    {
      siteName: "MakeUseOf",
      articleTitle: "The Best Photo Compression Tools You're Not Using",
      articleUrl: "https://www.makeuseof.com/best-photo-compression-tools/",
      contactName: "Alvin Wanjala",
      contactEmail: null,
      contactLinkedin: null,
      status: "to_send",
    },
    {
      siteName: "Compresto",
      articleTitle: "Best Image Compressor Software in 2026",
      articleUrl: "https://compresto.app/blog/image-compressor-software",
      contactName: null,
      contactEmail: null,
      contactLinkedin: null,
      status: "to_send",
    },
    {
      siteName: "ImageOptimizerPro",
      articleTitle: "Best TinyPNG Alternatives for Faster Compression 2026",
      articleUrl: "https://imageoptimizerpro.ai/blog/best-tinypng-alternatives/",
      contactName: "Ishan Makkar",
      contactEmail: null,
      contactLinkedin: null,
      status: "to_send",
    },
    {
      siteName: "DDaverse",
      articleTitle: "How to Compress Images Without Losing Quality",
      articleUrl: "https://www.ddaverse.com/blog/how-to-compress-images-without-losing-quality",
      contactName: "Deepak Singh Chaudhary",
      contactEmail: "ddaverse2529@gmail.com",
      contactLinkedin: null,
      status: "to_send",
    },
    {
      siteName: "Digital ToolPad",
      articleTitle: "Top 12 Best Free Image Resizer Tools for 2026",
      articleUrl: "https://www.digitaltoolpad.com/blog/free-image-resizer",
      contactName: "Arman",
      contactEmail: null,
      contactLinkedin: null,
      status: "to_send",
    },
    {
      siteName: "Soona",
      articleTitle: "The 9 Best Image Resizer Tools in 2026",
      articleUrl: "https://soona.co/blog/the-9-best-image-resizer-tools-in-2026",
      contactName: "Claire Oswald",
      contactEmail: null,
      contactLinkedin: null,
      status: "to_send",
    },
    {
      siteName: "HitPaw",
      articleTitle: "Top 10 Bulk Image Resizers Online and on Desktop",
      articleUrl: "https://www.hitpaw.com/photo-tips/bulk-image-resizer.html",
      contactName: "Daniel Walker",
      contactEmail: null,
      contactLinkedin: null,
      status: "to_send",
    },
    {
      siteName: "PixelBin",
      articleTitle: "12 best AI image editors in 2026",
      articleUrl: "https://www.pixelbin.io/blog/best-ai-image-editors",
      contactName: "Pooja Mishra",
      contactEmail: null,
      contactLinkedin: null,
      status: "to_send",
    },
    {
      siteName: "CyberPanel",
      articleTitle: "5 Best WordPress Image Optimizer Plugins for 2026",
      articleUrl: "https://cyberpanel.net/blog/best-wordpress-image-optimizer-plugins",
      contactName: "Areeba Nauman",
      contactEmail: null,
      contactLinkedin: null,
      status: "to_send",
    },
    {
      siteName: "Jetpack",
      articleTitle: "8 Best WordPress Image Optimization Plugins",
      articleUrl: "https://jetpack.com/resources/best-wordpress-image-optimization-plugins/",
      contactName: "Jen Swisher",
      contactEmail: null,
      contactLinkedin: null,
      status: "to_send",
    },
    {
      siteName: "Bluehost",
      articleTitle: "7 Best WordPress Image Optimization Plugins for 2026",
      articleUrl: "https://www.bluehost.com/blog/best-wordpress-image-optimization-plugins/",
      contactName: "Sugandh Kumari",
      contactEmail: null,
      contactLinkedin: null,
      status: "to_send",
    },
    {
      siteName: "WPDiscounts",
      articleTitle: "WordPress Image Optimization Plugins",
      articleUrl: "https://wpdiscounts.io/blog/best-wordpress-image-optimization-plugins/",
      contactName: "Jon Zaidi",
      contactEmail: "affiliate@wpdiscounts.io",
      contactLinkedin: null,
      status: "to_send",
    },
    {
      siteName: "NodeSure",
      articleTitle: "10 Best AI Image Editing Tools in 2026",
      articleUrl: "https://www.nodesure.com/10-best-ai-image-editing-tools-in-2026-for-designers-creators/",
      contactName: "Navneet Singh Chouhan",
      contactEmail: "navneet@nodesure.com",
      contactLinkedin: null,
      status: "to_send",
    },
    {
      siteName: "Them Frames",
      articleTitle: "Best AI Photo Editor in 2026",
      articleUrl: "https://themframes.com/features/best-ai-photo-editor/",
      contactName: "Dan Ginn",
      contactEmail: null,
      contactLinkedin: null,
      status: "to_send",
    },
    {
      siteName: "TeamUpdraft",
      articleTitle: "Best image optimization plugins for WordPress",
      articleUrl: "https://teamupdraft.com/blog/best-image-optimization-plugin-wordpress/",
      contactName: "Becks Faulkner",
      contactEmail: null,
      contactLinkedin: null,
      status: "to_send",
    },
    {
      siteName: "PluginTheme",
      articleTitle: "WordPress Image Optimization 2026",
      articleUrl: "https://plugintheme.net/blog/wordpress-image-optimization-guide-2026",
      contactName: "Erik Keller",
      contactEmail: null,
      contactLinkedin: null,
      status: "to_send",
    },
    {
      siteName: "BulkImagePro",
      articleTitle: "AVIF Image Format: Next-Gen Compression",
      articleUrl: "https://bulkimagepro.com/articles/avif-image-compression/",
      contactName: "Kal W",
      contactEmail: null,
      contactLinkedin: null,
      status: "to_send",
    },
    {
      siteName: "The Debuggers",
      articleTitle: "Best Image Converter Tools Online in 2026",
      articleUrl: "https://thedebuggersitsolutions.com/blog/best-image-converter-tools-online-2026",
      contactName: null,
      contactEmail: null,
      contactLinkedin: null,
      status: "to_send",
    },
    {
      siteName: "Zapier",
      articleTitle: "How to Quickly Optimize Images for Web SEO",
      articleUrl: "https://zapier.com/blog/quickly-optimize-images/",
      contactName: "Jamie Irish",
      contactEmail: null,
      contactLinkedin: null,
      status: "to_send",
    },
    {
      siteName: "TechPP",
      articleTitle: "This Free Google Tool Replaced TinyPNG for Me",
      articleUrl: "https://techpp.com/2026/03/11/squoosh-vs-tinypng/",
      contactName: null,
      contactEmail: null,
      contactLinkedin: null,
      status: "to_send",
    },
    {
      siteName: "NexifyRank",
      articleTitle: "Best WordPress Image Optimization Plugins",
      articleUrl: "https://nexifyrank.com/best-wordpress-image-optimization-plugins/",
      contactName: "Jack",
      contactEmail: null,
      contactLinkedin: null,
      status: "to_send",
    },
    {
      siteName: "Pixotter",
      articleTitle: "Compress PNG Files Without Losing Quality",
      articleUrl: "https://pixotter.com/blog/compress-png/",
      contactName: null,
      contactEmail: null,
      contactLinkedin: null,
      status: "to_send",
    },
    {
      siteName: "G2 Alternatives",
      articleTitle: "Top 10 TinyPNG Alternatives & Competitors",
      articleUrl: "https://www.g2.com/products/tinypng/competitors/alternatives",
      contactName: null,
      contactEmail: null,
      contactLinkedin: null,
      status: "to_send",
    },
    {
      siteName: "Authentic Jobs",
      articleTitle: "The 5 Best Free Image Optimizer Tools",
      articleUrl: "https://authenticjobs.com/the-5-best-free-image-optimizer-tools/",
      contactName: null,
      contactEmail: null,
      contactLinkedin: null,
      status: "to_send",
    },
    {
      siteName: "FinancesOnline",
      articleTitle: "SammaPix Review",
      articleUrl: "https://financesonline.com",
      contactName: null,
      contactEmail: null,
      contactLinkedin: null,
      status: "to_send",
    },
  ];

  for (const target of outreachTargets) {
    await db
      .insert(growthOutreachTargets)
      .values(target)
      .onConflictDoNothing();
  }

  console.log(`Inserted ${outreachTargets.length} outreach targets`);

  console.log("Seeding directory submissions...");

  const directories = [
    {
      directoryName: "G2",
      directoryUrl: "https://g2.com",
      status: "listed",
    },
    {
      directoryName: "SaaSHub",
      directoryUrl: "https://saashub.com",
      status: "listed",
    },
    {
      directoryName: "AlternativeTo",
      directoryUrl: "https://alternativeto.net",
      status: "submitted",
    },
    {
      directoryName: "Uneed",
      directoryUrl: "https://uneed.best",
      status: "submitted",
    },
    {
      directoryName: "Capterra",
      directoryUrl: "https://capterra.com",
      status: "to_submit",
    },
    {
      directoryName: "Product Hunt",
      directoryUrl: "https://producthunt.com",
      status: "to_submit",
    },
  ];

  for (const dir of directories) {
    await db
      .insert(growthDirectorySubmissions)
      .values(dir)
      .onConflictDoNothing();
  }

  console.log(`Inserted ${directories.length} directory submissions`);
  console.log("Seed complete.");
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
