export type PostTag = "Tools" | "SEO" | "Performance" | "Privacy" | "Workflow" | "Creative";

export interface Post {
  slug: string;
  title: string;
  description: string;
  date: string;
  tags: PostTag[];
  coverImage?: string; // Phase 2: "/blog/covers/[slug].webp"
}

export const POSTS: Post[] = [
  { slug: "how-to-convert-word-to-pdf-online-free", title: "How to Convert Word to PDF Online (Free, No Upload)", description: "Convert .docx files to PDF in your browser without uploading them anywhere. Why Adobe and Smallpdf upload your file, how to do it privately, formatting fidelity tips, batch conversion, and FAQ.", date: "2026-08-23", tags: ["Tools", "Workflow"], coverImage: "https://images.pexels.com/photos/590016/pexels-photo-590016.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "how-to-open-jar-files-online", title: "How to Open JAR Files Online (Free, No Upload) [2026]", description: "Open and extract Java .jar and .war archives in your browser without installing Java or WinZip. View class files, resources, and META-INF. 100% in-browser, no upload.", date: "2026-08-23", tags: ["Tools", "Workflow"], coverImage: "https://images.pexels.com/photos/574071/pexels-photo-574071.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "how-to-open-gz-files-online", title: "How to Open GZ Files Online (Free, No Upload) [2026]", description: "Open and extract .gz and .gzip files in your browser without installing any software. Supports plain GZ and tar.gz. 100% in-browser, no upload, no signup.", date: "2026-08-23", tags: ["Tools", "Workflow"], coverImage: "https://images.pexels.com/photos/1181298/pexels-photo-1181298.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "how-to-open-xz-files-online", title: "How to Open XZ Files Online (Free, No Upload) [2026]", description: "Open and extract .xz files (LZMA2 compression) in your browser without installing any software. Supports plain XZ and tar.xz. 100% in-browser, no upload, no signup.", date: "2026-08-23", tags: ["Tools", "Workflow"], coverImage: "https://images.pexels.com/photos/1181671/pexels-photo-1181671.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "how-to-view-and-convert-stl-files-online", title: "How to View and Convert STL Files Online (Free, No Upload) [2026]", description: "View STL, OBJ, GLB and PLY files in your browser with a WebGL viewer. Convert STL to OBJ or GLB for Blender and the web. No upload, no software install. Works with proprietary CAD files. Free.", date: "2026-08-22", tags: ["Tools", "Workflow"], coverImage: "https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "how-to-format-json-online-free", title: "How to Format and Validate JSON Online Free (No Upload) [2026]", description: "Format, prettify, and validate any JSON string instantly in your browser. No upload, no server, no account. Covers trailing commas, unquoted keys, single quotes, and why not to paste production data into random sites.", date: "2026-08-22", tags: ["Tools", "Workflow"], coverImage: "https://images.pexels.com/photos/1181298/pexels-photo-1181298.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "common-json-errors-and-how-to-fix-them", title: "Common JSON Errors and How to Fix Them (2026)", description: "Reference guide to every common JSON.parse error: Unexpected token, Unexpected end of input, trailing comma, unquoted keys, single quotes, duplicate keys. Cause, fix, and example for each.", date: "2026-08-22", tags: ["Tools", "Workflow"], coverImage: "https://images.pexels.com/photos/1181671/pexels-photo-1181671.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "avif-vs-webp-vs-jpeg-benchmark-2026", title: "AVIF vs WebP vs JPEG: Real Benchmark (2026)", description: "Original benchmark at equal visual quality (SSIM 0.98): AVIF is 27% smaller than JPEG and 29% smaller than WebP. Full data and reproducible method.", date: "2026-08-09", tags: ["Performance", "Tools"], coverImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80" },
  { slug: "what-are-content-credentials-c2pa", title: "What Are Content Credentials (C2PA)? 2026 Guide", description: "Content Credentials (C2PA) are tamper-evident provenance records for media. How they differ from EXIF and SynthID, how to view them, why they matter in 2026.", date: "2026-08-09", tags: ["Privacy", "Workflow"], coverImage: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&q=80" },
  { slug: "how-to-check-if-image-is-ai-generated", title: "How to Check if an Image Is AI-Generated (2026)", description: "Layered guide to telling if an image is AI made: Content Credentials (C2PA), SynthID, metadata and visual tells, with honest limits. Free tools, no upload.", date: "2026-08-09", tags: ["Privacy", "Workflow"], coverImage: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&q=80" },
  { slug: "us-passport-photo-requirements-2026", title: "US Passport Photo Requirements 2026 (2x2, Exact)", description: "US passport photo is 2x2 inches, 600x600 to 1200x1200 px, white background. AI-edited photos are rejected in 2026. Make a compliant photo free, no upload.", date: "2026-08-09", tags: ["Tools", "Workflow"], coverImage: "https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=800&q=80" },
  { slug: "dv-lottery-photo-requirements", title: "DV Lottery Photo Requirements 2026 (Green Card)", description: "Diversity Visa lottery photo: 600x600 px, 240 KB max, white background. Get the size and file exactly right free, no upload, no disqualification.", date: "2026-08-09", tags: ["Tools", "Workflow"], coverImage: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=800&q=80" },
  { slug: "canada-passport-photo-requirements-2026", title: "Canada Passport Photo Requirements 2026 (50x70mm)", description: "Canadian passport photo is a unique 50x70 mm with a white background. Exact IRCC rules and how to get the size right free, no upload.", date: "2026-08-09", tags: ["Tools", "Workflow"], coverImage: "https://images.unsplash.com/photo-1621768216002-5ac171661d8c?w=800&q=80" },
  { slug: "uk-passport-photo-requirements-2026", title: "UK Passport Photo Requirements 2026 (Size & Rules)", description: "UK passport photo is 45x35 mm (600x750 px digital) on a light grey or cream background. Exact rules and how to prepare one free, no upload.", date: "2026-08-09", tags: ["Tools", "Workflow"], coverImage: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&q=80" },
  { slug: "resize-photo-signature-indian-exams", title: "Resize Photo & Signature for Indian Exams (2026 Guide)", description: "Exact photo and signature sizes for UPSC, SSC, IBPS, RRB and state exams, and how to hit the pixels and KB free in your browser, no upload.", date: "2026-08-09", tags: ["Tools", "Workflow"], coverImage: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&q=80" },
  { slug: "upsc-photo-signature-size-2026", title: "UPSC Photo & Signature Size 2026 (Exact Specs)", description: "UPSC 2026 photo is 200x230 px, 20 to 300 KB, JPEG, white background. Signature 20 to 100 KB. Exact rules and how to make them free, no upload.", date: "2026-08-09", tags: ["Tools", "Workflow"], coverImage: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&q=80" },
  { slug: "resize-photo-to-20kb", title: "How to Resize a Photo to 20KB Online Free (No Upload)", description: "Resize or compress any photo to an exact 20KB, 50KB or 100KB in your browser, free, no upload. For exam forms and government portals.", date: "2026-08-09", tags: ["Tools", "Workflow"], coverImage: "https://images.unsplash.com/photo-1616469829581-73993eb86b02?w=800&q=80" },
  { slug: "eu-ai-act-label-ai-content", title: "EU AI Act: Do You Have to Label AI Content? (2026)", description: "EU AI Act Article 50 requires visible disclosure on AI-generated images, audio and video since 2 August 2026. Who must comply, what counts as a label, and how to do it free.", date: "2026-08-08", tags: ["Workflow", "Privacy"], coverImage: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&q=80" },
  { slug: "how-to-add-made-with-ai-label", title: "How to Add a Made with AI Label to Images (Free)", description: "Add a visible Made with AI label to your images for free, in your browser, no upload. Step by step to comply with the EU AI Act disclosure rule.", date: "2026-08-08", tags: ["Creative", "Workflow"], coverImage: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&q=80" },
  { slug: "password-generator-online", title: "Free Password Generator Online — No Upload [2026]", description: "Generate strong random passwords in your browser. No upload, no server. crypto.getRandomValues, strength meter, custom options. Free.", date: "2026-08-04", tags: ["Tools", "Privacy"], coverImage: "https://images.pexels.com/photos/5380642/pexels-photo-5380642.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "strong-password-generator", title: "Strong Password Generator — Length Wins [2026]", description: "Why password length beats complexity. Generate secure 16+ char passwords in your browser. No upload, no server. Free, instantly.", date: "2026-08-04", tags: ["Tools", "Privacy"], coverImage: "https://images.pexels.com/photos/60504/security-protection-anti-virus-software-60504.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "hash-generator-online", title: "Hash Generator Online — MD5, SHA, SHA-512 Free [2026]", description: "Generate MD5, SHA-256, SHA-512 hashes. No upload, no account. Free.", date: "2026-08-04", tags: ["Tools", "Privacy"], coverImage: "https://images.pexels.com/photos/60504/security-protection-anti-virus-software-60504.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "generate-sha256-md5-online", title: "How to Generate a SHA-256 or MD5 Checksum Online Without Uploading [2026]", description: "Generate SHA-256 or MD5 checksums. Verify downloads. No upload. Free.", date: "2026-08-04", tags: ["Tools", "Privacy"], coverImage: "https://images.pexels.com/photos/1089438/pexels-photo-1089438.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "url-encode-decode-online", title: "URL Encode / Decode Online Free — Percent-Encoding Explained [2026]", description: "Encode or decode any URL online for free. Understand percent-encoding, reserved characters (%20 %2F %3F %26), encodeURIComponent vs encodeURI, and when to use each. 100% in your browser. No upload.", date: "2026-08-04", tags: ["Tools", "Workflow"], coverImage: "https://images.pexels.com/photos/270408/pexels-photo-270408.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "url-encoder-decoder-tool", title: "URL Encoder Decoder Tool — Encode & Decode URLs Online Without Installing Anything [2026]", description: "Encode or decode a URL online without installing any software. Step-by-step guide: encode a parameter with spaces and special characters, decode a received link, fix double encoding. 100% client-side. Free.", date: "2026-08-04", tags: ["Tools", "Workflow"], coverImage: "https://images.pexels.com/photos/574071/pexels-photo-574071.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "barcode-reader-online", title: "Barcode Reader Online — Decode Barcodes Free [2026]", description: "Decode barcodes from photos. EAN, UPC, CODE128, QR. Free.", date: "2026-08-04", tags: ["Tools", "Workflow"], coverImage: "https://images.pexels.com/photos/4483610/pexels-photo-4483610.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "scan-barcode-from-image", title: "How to Scan a Barcode from an Image or Photo (No Scanner App) [2026]", description: "Scan barcodes from photos. No app, no camera. Free.", date: "2026-08-04", tags: ["Tools", "Workflow"], coverImage: "https://images.pexels.com/photos/6169659/pexels-photo-6169659.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "barcode-generator-online", title: "Barcode Generator Online — Free Code128, EAN [2026]", description: "Generate CODE128, EAN, UPC barcodes. Download PNG/SVG. Free.", date: "2026-08-04", tags: ["Tools", "Workflow"], coverImage: "https://images.pexels.com/photos/5632381/pexels-photo-5632381.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "create-barcode-free", title: "Create Barcode Free — No Signup Required [2026]", description: "Create barcodes without signup. Choose format, download PNG/SVG. Free.", date: "2026-08-04", tags: ["Tools", "Workflow"], coverImage: "https://images.pexels.com/photos/6169668/pexels-photo-6169668.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "qr-code-reader-online", title: "QR Code Reader Online — Decode Free [2026]", description: "Read QR codes from images. No camera, no upload. Free.", date: "2026-08-04", tags: ["Tools", "Privacy"], coverImage: "https://images.pexels.com/photos/278430/pexels-photo-278430.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "scan-qr-code-from-image", title: "Scan QR Code from Screenshot (No Camera) [2026]", description: "Decode QR codes from images. No camera, no upload. Free.", date: "2026-08-04", tags: ["Tools", "Privacy"], coverImage: "https://images.pexels.com/photos/4386321/pexels-photo-4386321.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "qr-code-generator-online", title: "Free QR Code Generator Online — No Signup, No Expiry [2026]", description: "Create QR codes from URLs, text, email, Wi-Fi. Download PNG/SVG. Free.", date: "2026-08-04", tags: ["Tools", "Creative"], coverImage: "https://images.pexels.com/photos/278430/pexels-photo-278430.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "create-qr-code-no-signup", title: "Create QR Code Free — No Account, No Expiry [2026]", description: "Create QR codes without signup. Download PNG/SVG. Free.", date: "2026-08-04", tags: ["Tools", "Creative"], coverImage: "https://images.pexels.com/photos/4386321/pexels-photo-4386321.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "extract-ipa-online", title: "Extract an IPA File Online Free (No Upload) [2026]", description: "Extract iOS IPA files in your browser. Browse app files. No upload. Free.", date: "2026-08-04", tags: ["Tools"], coverImage: "https://images.pexels.com/photos/1181244/pexels-photo-1181244.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "open-ipa-file-online", title: "Open IPA File Online (No Xcode Needed) [2026]", description: "Open IPA files in your browser. Browse iOS app files. Free.", date: "2026-08-04", tags: ["Tools", "Workflow"], coverImage: "https://images.pexels.com/photos/574071/pexels-photo-574071.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "tar-to-zip-online", title: "Convert TAR to ZIP Online Free (No Upload) [2026]", description: "Convert TAR, TAR.GZ, TGZ, TAR.BZ2, TAR.XZ to ZIP. Free.", date: "2026-08-04", tags: ["Tools"], coverImage: "https://images.pexels.com/photos/207580/pexels-photo-207580.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "convert-tar-to-zip-no-upload", title: "Convert TAR to ZIP Online Free [2026]", description: "Convert TAR, TAR.GZ, TGZ, TAR.BZ2, TAR.XZ to ZIP. No upload. Free.", date: "2026-08-04", tags: ["Tools", "Workflow"], coverImage: "https://images.pexels.com/photos/1181671/pexels-photo-1181671.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "extract-iso-online", title: "Extract an ISO File Online Free (No Upload) [2026]", description: "Extract ISO disc images in your browser. Browse and download files. Free.", date: "2026-08-04", tags: ["Tools"], coverImage: "https://images.pexels.com/photos/1181316/pexels-photo-1181316.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "open-iso-file-online", title: "How to Open an ISO File Without Burning or Mounting [2026]", description: "Open ISO files without burning or mounting. Browse files in your browser. Free.", date: "2026-08-04", tags: ["Tools", "Workflow"], coverImage: "https://images.pexels.com/photos/1148820/pexels-photo-1148820.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "extract-apk-online", title: "Extract an APK File Online Free (No Upload) [2026]", description: "Extract APK files in your browser. Browse app data. No upload. Free.", date: "2026-08-04", tags: ["Tools"], coverImage: "https://images.pexels.com/photos/1181244/pexels-photo-1181244.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "open-apk-file-online", title: "How to Open an APK File Without Installing It [2026]", description: "View APK files in your browser. Browse app data. No upload. Free.", date: "2026-08-04", tags: ["Workflow"], coverImage: "https://images.pexels.com/photos/1181675/pexels-photo-1181675.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "extract-mcpack-online", title: "Open and Extract a .mcpack File Online Free [2026]", description: "Extract .mcpack files in your browser. Browse textures and assets. Free.", date: "2026-08-04", tags: ["Tools"], coverImage: "https://images.pexels.com/photos/7915437/pexels-photo-7915437.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "open-minecraft-mcworld-file", title: "How to Open a .mcworld File (Minecraft World) [2026]", description: "Extract .mcworld files in your browser. Browse world data and assets. Free.", date: "2026-08-04", tags: ["Tools", "Workflow"], coverImage: "https://images.pexels.com/photos/1148820/pexels-photo-1148820.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "7z-to-zip-online", title: "Convert 7Z to ZIP Online Free (No Upload) [2026]", description: "Convert 7Z to ZIP in your browser. No server, no signup. Free.", date: "2026-08-04", tags: ["Tools"], coverImage: "https://images.pexels.com/photos/1181675/pexels-photo-1181675.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "convert-7z-to-zip-no-upload", title: "How to Convert 7Z to ZIP Without Software [2026]", description: "Convert 7Z to ZIP in your browser. No server, no signup. Free.", date: "2026-08-04", tags: ["Tools", "Workflow"], coverImage: "https://images.pexels.com/photos/574071/pexels-photo-574071.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "rar-to-zip-online", title: "Convert RAR to ZIP Online Free (No Upload) [2026]", description: "Convert RAR to ZIP in your browser. No server, no signup. Free.", date: "2026-08-04", tags: ["Tools"], coverImage: "https://images.pexels.com/photos/1181671/pexels-photo-1181671.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "convert-rar-to-zip-no-upload", title: "How to Convert RAR to ZIP Without Uploading [2026]", description: "Convert RAR to ZIP in your browser. No server, no signup. Free.", date: "2026-08-04", tags: ["Tools", "Workflow"], coverImage: "https://images.pexels.com/photos/574071/pexels-photo-574071.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "txt-to-pdf-online-free", title: "Convert TXT to PDF Online Free (No Upload) [2026]", description: "Convert a .txt file or pasted text to a PDF in your browser. Runs via pdf-lib locally — the file never leaves your device. Choose font, page size, and margins. Free, no signup, no upload.", date: "2026-08-03", tags: ["Tools"], coverImage: "https://images.pexels.com/photos/4050315/pexels-photo-4050315.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "convert-text-to-pdf-no-upload", title: "How to Convert a Text File to PDF Without Uploading [2026]", description: "Convert any .txt file or pasted text to a shareable PDF in your browser — no upload, no server, no signup. Monospace Courier font preserves log and code alignment. Word wrap handles any line length. Free.", date: "2026-08-03", tags: ["Tools", "Workflow"], coverImage: "https://images.pexels.com/photos/1181271/pexels-photo-1181271.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "flatten-pdf-online-free", title: "Flatten a PDF Online Free (No Upload) [2026]", description: "Make any PDF non-editable by flattening it in your browser — no upload, no server, no signup. pdf-lib form.flatten() converts form fields into permanent, printed content. Honest about what flatten means and what it does not do. Free.", date: "2026-08-03", tags: ["Tools"], coverImage: "https://images.pexels.com/photos/6863183/pexels-photo-6863183.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "flatten-pdf-form-no-upload", title: "How to Flatten a PDF Form (No Upload) [2026]", description: "Flatten a fillable PDF form entirely in your browser — no upload, no server, no signup. pdf-lib form.flatten() locks all form fields permanently. Fields appear identical on every PDF reader. Flatten vs print-to-PDF explained. Free.", date: "2026-08-03", tags: ["Tools", "Workflow"], coverImage: "https://images.pexels.com/photos/4386431/pexels-photo-4386431.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "crop-pdf-online-free", title: "Crop a PDF Online Free (Trim Margins) [2026]", description: "Crop PDF margins per side — top, right, bottom, left — entirely in your browser via pdf-lib setCropBox. Preview with pdf.js. No upload, no signup, no server. Free.", date: "2026-08-03", tags: ["Tools"], coverImage: "https://images.pexels.com/photos/4050315/pexels-photo-4050315.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "crop-pdf-margins-no-upload", title: "How to Remove White Margins from a PDF (No Upload) [2026]", description: "Remove white margins from scanned PDFs or optimize for e-reader reading — entirely in your browser via pdf-lib setCropBox. Per-side crop, live pdf.js preview, no upload, no signup. Free.", date: "2026-08-03", tags: ["Tools", "Workflow"], coverImage: "https://images.pexels.com/photos/3807517/pexels-photo-3807517.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "reorder-pdf-pages-online", title: "Reorder PDF Pages Online Free [2026]", description: "Rearrange, sort, and reorder PDF pages entirely in your browser — drag and drop thumbnail grid powered by pdf.js and pdf-lib. Move pages up, down, to the top, or to the bottom. No upload, no signup. Free.", date: "2026-08-03", tags: ["Tools"], coverImage: "https://images.pexels.com/photos/6863183/pexels-photo-6863183.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "organize-pdf-pages-no-upload", title: "How to Organize PDF Pages Without Uploading [2026]", description: "Organize, move, and rearrange PDF pages entirely in your browser — drag and drop visual thumbnails, no file upload, no server. Powered by pdf.js and pdf-lib. Fix out-of-order scans, reorder contracts, move sections privately. Free.", date: "2026-08-03", tags: ["Tools", "Privacy"], coverImage: "https://images.pexels.com/photos/4792282/pexels-photo-4792282.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "sign-pdf-online-free", title: "Sign a PDF Online Free (No Upload) [2026]", description: "Add a visual signature to any PDF entirely in your browser — draw it by hand on a canvas or upload a signature image. Powered by pdf-lib. No upload, no server, no signup. Honest about visual vs certified digital signatures. Free.", date: "2026-08-03", tags: ["Privacy", "Tools"], coverImage: "https://images.pexels.com/photos/3760093/pexels-photo-3760093.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "add-signature-to-pdf-no-upload", title: "How to Add a Signature to a PDF Without Uploading It [2026]", description: "Insert a visual signature on a PDF entirely in your browser — draw by hand on a canvas or upload a signature image, positioned precisely on any page via pdf-lib. No upload, no server, no signup. Honest about visual vs certified digital signatures. Free.", date: "2026-08-03", tags: ["Privacy", "Tools"], coverImage: "https://images.pexels.com/photos/4427611/pexels-photo-4427611.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "add-watermark-to-pdf-online", title: "Add a Watermark to a PDF Online Free [2026]", description: "Stamp any PDF with a text watermark (CONFIDENTIAL, DRAFT, your name) or a logo image — entirely in your browser via pdf-lib. No upload, no server, no signup. Diagonal tile, opacity control, custom font size. Free.", date: "2026-08-03", tags: ["Privacy", "Tools"], coverImage: "https://images.pexels.com/photos/590016/pexels-photo-590016.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "watermark-pdf-no-upload", title: "Watermark a PDF Without Uploading It [2026]", description: "Add a CONFIDENTIAL, DRAFT, or logo watermark to a PDF entirely in your browser via pdf-lib. No file upload, no server, no signup. Diagonal tile, opacity control, text or image. Verify with DevTools. Free.", date: "2026-08-03", tags: ["Privacy", "Tools"], coverImage: "https://images.pexels.com/photos/6863183/pexels-photo-6863183.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "delete-pages-from-pdf-online", title: "Delete Pages from a PDF Online Free [2026]", description: "Remove one page or a range of pages from any PDF — entirely in your browser via pdf.js + pdf-lib. Thumbnail preview, range selection (e.g. 2, 5-7), no upload, no signup. Free.", date: "2026-08-03", tags: ["Privacy", "Tools"], coverImage: "https://images.pexels.com/photos/7433882/pexels-photo-7433882.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "remove-pdf-pages-no-upload", title: "Remove Pages from a PDF Without Uploading It [2026]", description: "Delete pages from contracts, bank statements, and confidential PDFs entirely in your browser. No upload, no server, no signup. Remove blank pages, duplicate scans, or sensitive sections privately. Free.", date: "2026-08-03", tags: ["Privacy"], coverImage: "https://images.pexels.com/photos/6863183/pexels-photo-6863183.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "photo-collage-maker-online", title: "Photo Collage Maker Online Free (No Upload) [2026]", description: "Combine multiple photos into one collage in your browser — no upload, no server, no signup. Choose 2, 3, 4, 6, or 9-grid layouts. Custom gap, background color, cover or contain fit. No watermark. Free.", date: "2026-08-03", tags: ["Creative", "Tools"], coverImage: "https://images.pexels.com/photos/1261731/pexels-photo-1261731.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "image-grid-maker-free", title: "How to Make an Image Grid Free (2x2, 3x3, 4x6) [2026]", description: "Create a precise image grid free — 2x2, 3x3, and more — in your browser via Canvas. Custom gap, background color, cover or contain. No upload, no watermark, no signup. Free.", date: "2026-08-03", tags: ["Creative", "Tools"], coverImage: "https://images.pexels.com/photos/3756879/pexels-photo-3756879.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "image-to-base64-online", title: "Convert an Image to Base64 Online Free [2026]", description: "Encode any image to Base64, Data URI, CSS background-image, or HTML img src — 100% in your browser via FileReader. No upload, no server, no signup. Reverse decode included. Free.", date: "2026-08-03", tags: ["Performance", "Tools"], coverImage: "https://images.pexels.com/photos/1181298/pexels-photo-1181298.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "base64-to-image-converter", title: "Base64 to Image: Decode & Download Free [2026]", description: "Paste any Base64 string or Data URI and decode it back to a previewable, downloadable PNG or JPG — 100% in your browser. No upload, no server, no signup. Also supports reverse encode. Free.", date: "2026-08-03", tags: ["Performance", "Workflow"], coverImage: "https://images.pexels.com/photos/1181244/pexels-photo-1181244.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "add-text-to-image-online", title: "Add Text to an Image Online Free [2026]", description: "Add text to any image online — entirely in your browser via Canvas. Choose font, size, color, outline, and position. Live preview. No upload, no server, no signup. Free.", date: "2026-08-03", tags: ["Creative", "Tools"], coverImage: "https://images.pexels.com/photos/3184418/pexels-photo-3184418.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "add-caption-to-photo-free", title: "How to Add a Caption to a Photo Free [2026]", description: "Add a caption to any photo free — entirely in your browser via Canvas. Text outline for legibility on any background. Social, meme, watermark. No upload, no signup. Free.", date: "2026-08-03", tags: ["Creative", "Tools"], coverImage: "https://images.pexels.com/photos/1181396/pexels-photo-1181396.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "crop-image-into-circle-online", title: "Crop an Image into a Circle Online Free [2026]", description: "Crop any image into a perfect circle online — entirely in your browser via Canvas. No upload, no server, no signup. Output is a transparent PNG. Batch + ZIP. Free.", date: "2026-08-03", tags: ["Creative", "Tools"], coverImage: "https://images.pexels.com/photos/3184418/pexels-photo-3184418.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "round-image-corners-free", title: "How to Round the Corners of an Image Free [2026]", description: "Add rounded corners to any image free — entirely in your browser via Canvas. No upload, no server, no signup. Output is a transparent PNG. Choose your radius. Batch + ZIP. Free.", date: "2026-08-03", tags: ["Creative", "Tools"], coverImage: "https://images.pexels.com/photos/196644/pexels-photo-196644.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "add-border-to-image-online", title: "Add a Border to an Image Online Free [2026]", description: "Add a white, black, or custom-color border to any image online — entirely in your browser via Canvas. No upload, no server, no signup. Choose expand or inset, pick any color and thickness. Batch + ZIP. Free.", date: "2026-08-03", tags: ["Creative", "Tools"], coverImage: "https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "add-frame-to-photo-free", title: "How to Add a Frame to a Photo Free (Any Color) [2026]", description: "Add a frame or border to any photo free — white for Instagram, black for print, Polaroid-style, or any custom color. No upload, no server, runs in your browser via Canvas. Batch + ZIP. Free.", date: "2026-08-03", tags: ["Creative"], coverImage: "https://images.pexels.com/photos/1647972/pexels-photo-1647972.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "flip-image-online-no-upload", title: "Flip an Image Online Without Uploading It [2026]", description: "Mirror or flip any image horizontally or vertically — entirely in your browser via Canvas. No upload, no server, no signup. Batch flip 20 photos at once and download a ZIP. Free.", date: "2026-08-03", tags: ["Tools"], coverImage: "https://images.pexels.com/photos/3094218/pexels-photo-3094218.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "mirror-photo-online-free", title: "How to Mirror a Photo Free (Horizontal & Vertical) [2026]", description: "Mirror any photo free in your browser — horizontal flip, vertical flip, or both. Fix mirrored selfies, create reflection effects, correct reversed scans. No upload, no signup, batch + ZIP. Free.", date: "2026-08-03", tags: ["Creative", "Tools"], coverImage: "https://images.pexels.com/photos/1209843/pexels-photo-1209843.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "rotate-image-online-no-upload", title: "Rotate an Image Online Without Uploading It [2026]", description: "Rotate images 90, 180, or 270 degrees — or any custom angle — entirely in your browser via Canvas. No upload, no server, no signup. Batch rotate 20 photos at once and download a ZIP. Free.", date: "2026-08-03", tags: ["Tools"], coverImage: "https://images.pexels.com/photos/1983032/pexels-photo-1983032.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "how-to-rotate-a-photo-free", title: "How to Rotate a Photo Free (Batch, Any Angle) [2026]", description: "Rotate one photo or a batch of 20 at any angle — 90, 180, 270, or a custom degree — free in your browser. No upload, no app install, no signup. Straighten scans, fix crooked horizons, correct EXIF orientation. ZIP download.", date: "2026-08-03", tags: ["Tools"], coverImage: "https://images.pexels.com/photos/3761508/pexels-photo-3761508.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "password-protect-pdf-online-no-upload", title: "Password Protect a PDF Online Without Uploading It [2026]", description: "Add an open password to any PDF in your browser — no upload, no server, no signup. Encryption runs 100% client-side via @cantoo/pdf-lib. Honest about what happens if you forget the password. Free.", date: "2026-08-03", tags: ["Privacy", "Tools"], coverImage: "https://images.pexels.com/photos/4386367/pexels-photo-4386367.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "add-password-to-pdf-free", title: "How to Add a Password to a PDF Free [2026]", description: "Add a password to any PDF free, entirely in your browser. No upload to unknown sites. Explains open password vs owner password, the risk of uploading sensitive PDFs, and what happens if you forget. Free, no signup.", date: "2026-08-03", tags: ["Privacy", "Tools"], coverImage: "https://images.pexels.com/photos/6963944/pexels-photo-6963944.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "add-page-numbers-to-pdf-online", title: "How to Add Page Numbers to a PDF Online Free [2026]", description: "Add page numbers to any PDF in your browser — no upload, no server, no signup. Choose position, format (1, 1/N, Page 1 of N), font size, and start number. Text stays selectable. Free.", date: "2026-08-03", tags: ["Tools", "Workflow"], coverImage: "https://images.pexels.com/photos/4498362/pexels-photo-4498362.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "number-pdf-pages-no-upload", title: "Number PDF Pages Without Uploading (Private, Free) [2026]", description: "Add page numbers to a PDF entirely in your browser — no file upload, no server, no signup. Custom start number, multiple formats, six positions. Ideal for theses, legal briefs, and confidential reports. Free.", date: "2026-08-03", tags: ["Privacy", "Tools"], coverImage: "https://images.pexels.com/photos/5668882/pexels-photo-5668882.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "unlock-pdf-online-no-upload", title: "Unlock a PDF Online Without Uploading It [2026]", description: "Remove PDF restrictions (printing, copying, editing) in your browser with no file upload. Powered by pdf-lib. Honest about what it can and cannot unlock. Free, no signup.", date: "2026-08-03", tags: ["Privacy", "Tools"], coverImage: "https://images.pexels.com/photos/5668473/pexels-photo-5668473.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "remove-pdf-password-restrictions", title: "How to Remove PDF Restrictions (Printing, Copying, Editing) [2026]", description: "Enable printing, copying, and editing on a restricted PDF — free, in your browser, no upload. Explains owner-password vs user-password. Cannot crack open-password encryption. Honest guide.", date: "2026-08-03", tags: ["Privacy", "Tools"], coverImage: "https://images.pexels.com/photos/4065626/pexels-photo-4065626.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "rotate-pdf-online-no-upload", title: "Rotate a PDF Online Without Uploading It [2026]", description: "Rotate a PDF page by page or all at once — 90, 180, or 270 degrees. Runs entirely in your browser via pdf.js + pdf-lib. The rotation is permanent and saved into the file. No upload, no signup, free.", date: "2026-08-03", tags: ["Privacy", "Tools"], coverImage: "https://images.pexels.com/photos/3760067/pexels-photo-3760067.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "how-to-rotate-pdf-pages-permanently", title: "How to Rotate PDF Pages Permanently and Save [2026]", description: "Rotate a PDF and have the rotation actually stick — not flip back when you close it. The reason why Preview and Chrome rotate only temporarily, and how to save the rotation permanently into the file. Free, no upload.", date: "2026-08-03", tags: ["Tools", "Workflow"], coverImage: "https://images.pexels.com/photos/590016/pexels-photo-590016.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "compress-pdf-online-no-upload", title: "Compress a PDF Online Without Uploading It [2026]", description: "Compress a PDF in your browser with zero upload. Runs via pdf.js + pdf-lib locally. Ideal for scanned PDFs and image-heavy files. Honest about text-only PDFs. Free, no signup.", date: "2026-08-03", tags: ["Privacy", "Tools"], coverImage: "https://images.pexels.com/photos/3759098/pexels-photo-3759098.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "reduce-pdf-file-size-for-email", title: "How to Reduce PDF File Size for Email [2026]", description: "PDF too big to send by email? Compress it in your browser — no upload, no signup. Works best on scanned PDFs and image-heavy files. See before/after size, then download. Free.", date: "2026-08-03", tags: ["Tools", "Performance"], coverImage: "https://images.pexels.com/photos/1591062/pexels-photo-1591062.jpeg?auto=compress&cs=tinysrgb&w=1200" },
  { slug: "apply-lut-batch-photos-free-2026", title: "How to Apply a LUT to a Batch of Photos Free [2026]", description: "Apply one .cube LUT to 50 photos at once. Free, no Lightroom needed. Compare batch workflows: SammaPix, Lightroom, Premiere, DaVinci, FFmpeg.", date: "2026-05-18", tags: ["Tools"], coverImage: "https://images.pexels.com/photos/3617500/pexels-photo-3617500.jpeg?auto=compress&w=1200" },
  { slug: "extract-lut-from-photo-free-2026", title: "How to Extract a LUT from a Photo Free [2026]", description: "Turn any photo into a real 3D LUT in 30 seconds. Free, browser-based, exports .cube for Lightroom and Premiere. Step-by-step guide with examples.", date: "2026-05-18", tags: ["Tools"], coverImage: "https://images.pexels.com/photos/1647962/pexels-photo-1647962.jpeg?auto=compress&w=1200" },
  { slug: "does-imessage-strip-exif-metadata", title: "Does iMessage Strip EXIF Metadata? Honest 2026 Answer", description: "iMessage does NOT strip EXIF — your GPS coordinates travel with every photo. Here is the truth + the iOS toggle that fixes it in 5 seconds.", date: "2026-05-17", tags: ["Privacy"], coverImage: "https://images.pexels.com/photos/7794437/pexels-photo-7794437.jpeg?auto=compress&cs=tinysrgb&w=800&q=80" },
  { slug: "does-reddit-strip-exif-metadata", title: "Does Reddit Strip EXIF Metadata? Honest 2026 Answer", description: "Reddit strips EXIF on most uploads — but a real HackerOne bug exposed GPS via HEIC conversion. The history, the current status, and what to do.", date: "2026-05-17", tags: ["Privacy"], coverImage: "https://images.pexels.com/photos/1170412/pexels-photo-1170412.jpeg?auto=compress&cs=tinysrgb&w=800&q=80" },
  { slug: "does-telegram-strip-exif-metadata", title: "Does Telegram Strip EXIF Metadata? Honest 2026 Answer", description: "Telegram strips EXIF only when you compress — send as file and full GPS coordinates travel intact. The 5-second trap most users fall into, and how to avoid it.", date: "2026-05-17", tags: ["Privacy"], coverImage: "https://images.pexels.com/photos/1851415/pexels-photo-1851415.jpeg?auto=compress&cs=tinysrgb&w=800&q=80" },
  { slug: "does-signal-strip-exif-metadata", title: "Does Signal Strip EXIF Metadata? Honest 2026 Answer", description: "Signal is the only major messaging app that strips EXIF by default — and the only one that never keeps it server-side. Here is what is true and the open bug.", date: "2026-05-17", tags: ["Privacy"], coverImage: "https://images.pexels.com/photos/4348404/pexels-photo-4348404.jpeg?auto=compress&cs=tinysrgb&w=800&q=80" },
  { slug: "does-discord-strip-exif-metadata", title: "Does Discord Strip EXIF Metadata? Honest 2026 Answer", description: "Everyone claims Discord strips EXIF — but Discord has never documented it. We mapped what 6 sources say, the file-attachment loophole, and what to do instead.", date: "2026-05-17", tags: ["Privacy"], coverImage: "https://images.pexels.com/photos/4348401/pexels-photo-4348401.jpeg?auto=compress&cs=tinysrgb&w=800&q=80" },
  { slug: "ai-photo-renamer-custom-directive", title: "AI Photo Renamer with Custom Directives: Brand-Aware, Ecommerce, Pinterest Style (2026)", description: "Most AI photo renamers generate the same generic descriptive names for everyone. Here is how custom directives let you bias the AI toward your naming style — brand-first, ecommerce, Pinterest, niche keywords.", date: "2026-04-29", tags: ["SEO"], coverImage: "https://images.pexels.com/photos/4144923/pexels-photo-4144923.jpeg?auto=compress&cs=tinysrgb&w=800" },
  { slug: "upscale-image-ai-free-2026", title: "AI Image Upscaler Free 2026: Real Benchmark 2x vs 4x vs 8x", description: "How AI upscaling actually works in 2026, which models produce the best results, and how to upscale 2x/4x/8x for free without paying Topaz.", date: "2026-04-23", tags: ["Performance", "Tools"], coverImage: "https://images.pexels.com/photos/3183150/pexels-photo-3183150.jpeg?auto=compress&cs=tinysrgb&w=800" },
  { slug: "extract-brand-colors-from-image-2026", title: "Extract Brand Colors from Any Image: Free HEX/RGB/HSL Picker [2026]", description: "How to pull exact HEX, RGB, or HSL values from any image plus build a 6-color brand palette — free, in your browser, no upload.", date: "2026-04-22", tags: ["Creative", "Workflow"], coverImage: "https://images.pexels.com/photos/1292241/pexels-photo-1292241.jpeg?auto=compress&cs=tinysrgb&w=800" },
  { slug: "favicon-best-practices-2026", title: "Favicon Best Practices 2026: 4 Sizes + Animated Browser Support", description: "Most favicon guides list 22 sizes — you only need 4. The exact PNG/SVG/ICO setup, animated favicon browser support, dark mode, iOS, and PWA — with the 4 HTML tags to copy-paste.", date: "2026-04-22", tags: ["Performance"], coverImage: "https://images.pexels.com/photos/196655/pexels-photo-196655.jpeg?auto=compress&cs=tinysrgb&w=800" },
  { slug: "merge-pdfs-privately-no-upload", title: "Merge PDFs Privately: No Upload, No Adobe [2026 Guide]", description: "Most free PDF mergers upload your files to a server. For invoices, contracts, and tax returns that is unacceptable. Here is how to merge PDFs entirely in your browser.", date: "2026-04-22", tags: ["Privacy"], coverImage: "https://images.pexels.com/photos/955389/pexels-photo-955389.jpeg?auto=compress&cs=tinysrgb&w=800" },
  { slug: "gif-to-mp4-stop-using-gifs-2026", title: "GIF to MP4: Stop Using Animated GIFs in 2026", description: "Animated GIFs are 10 to 20x larger than MP4 at the same visual quality. Why MP4/WebM replaced GIF, how to convert, and where GIF still wins.", date: "2026-04-22", tags: ["Performance"], coverImage: "https://images.pexels.com/photos/2873486/pexels-photo-2873486.jpeg?auto=compress&cs=tinysrgb&w=800" },
  { slug: "svg-to-png-complete-guide-developers", title: "SVG to PNG: Complete Guide for Developers [2026]", description: "The developer guide to rasterizing SVG into PNG in 2026: intrinsic sizes, @2x/@3x scaling, favicon packs, transparency, and the pitfalls most tutorials skip.", date: "2026-04-22", tags: ["Performance"], coverImage: "https://images.pexels.com/photos/11035380/pexels-photo-11035380.jpeg?auto=compress&cs=tinysrgb&w=800" },
  { slug: "png-to-jpg-vs-webp-2026", title: "PNG to JPG vs WebP: Which One Should You Actually Use in 2026", description: "Should you convert PNG to JPG or WebP? Real benchmark on 50 images plus a decision framework. WebP beats JPG in 9 out of 10 cases.", date: "2026-04-22", tags: ["Performance"], coverImage: "https://images.pexels.com/photos/574071/pexels-photo-574071.jpeg?auto=compress&cs=tinysrgb&w=800" },
  { slug: "batch-watermark-photos-free-guide", title: "How to Batch Watermark Photos Free [2026 Guide]", description: "Add watermarks to 20 photos at once — free, no Photoshop, no upload. Text or logo watermark in your browser.", date: "2026-04-18", tags: ["Tools"], coverImage: "https://images.pexels.com/photos/1264210/pexels-photo-1264210.jpeg?auto=compress&cs=tinysrgb&w=800" },
  { slug: "heic-to-webp-converter-guide", title: "HEIC to WebP Converter: Why You Should Skip JPG in 2026", description: "Converting HEIC to JPG is a mistake. HEIC to WebP preserves more quality, produces smaller files, and WebP has 97%+ browser support.", date: "2026-04-05", tags: ["Performance"], coverImage: "https://images.unsplash.com/photo-1512499617640-c74ae3a79d37?w=800&q=80" },
  { slug: "optimize-images-shopify-free-guide", title: "Optimize Images for Shopify: Free Guide [2026]", description: "Learn how to optimize images for Shopify in 2026. Resize, compress, and convert to WebP for free — before uploading. Exact size specs and benchmarks.", date: "2026-04-14", tags: ["Performance"], coverImage: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80" },
  { slug: "webp-vs-avif-vs-jpeg-comparison", title: "AVIF vs WebP vs JPEG: Best Image Format 2026", description: "AVIF vs WebP vs JPEG compared with real benchmarks, browser support data, and an interactive tool. Find the right image format for your site in 2026.", date: "2026-04-13", tags: ["Performance"], coverImage: "https://images.unsplash.com/photo-1618477388954-7852f32655ec?w=800&q=80" },
  { slug: "best-free-remove-bg-alternatives-2026", title: "Best Free Remove.bg Alternatives 2026: 7 Background Removers Tested", description: "Remove.bg charges \u20AC0.36 per image. Here are 7 free alternatives for background removal tested on real photos \u2014 product shots, portraits, and complex edges.", date: "2026-04-12", tags: ["Tools"], coverImage: "https://images.unsplash.com/photo-1542831371-29b0f74f9713?w=800&q=80" },
  { slug: "instagram-image-quality-loss-fix", title: "Why Instagram Ruins Photo Quality + 30-Second Fix [2026]", description: "Why does Instagram ruin photo quality? It compresses up to 13x. The exact settings — dimensions, format, color profile — to upload photos that look sharp. Free fix in 30 seconds.", date: "2026-04-11", tags: ["Performance"], coverImage: "https://images.unsplash.com/photo-1611162616475-46b635cb6868?w=800&q=80" },
  { slug: "best-free-topaz-gigapixel-alternatives-2026", title: "Topaz Gigapixel Pricing 2026 vs 7 Free Alternatives (Tested)", description: "Topaz Gigapixel AI pricing 2026: $199/year for the official subscription. We tested 7 free alternatives on the same 50 photos — max scale (4x/8x), portrait quality, speed. The free winner that beat Gigapixel on faces.", date: "2026-04-10", tags: ["Tools"], coverImage: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&q=80" },
  { slug: "compress-photos-indian-exam-applications", title: "How to Compress Photos for Indian Exam Applications (JEE, NEET, UPSC, SSC)", description: "Step-by-step guide to compress and resize photos for JEE, NEET, UPSC, SSC, and GATE exam forms. Exact size requirements, signature compression, and free tools that work on your phone.", date: "2026-04-09", tags: ["Tools"], coverImage: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&q=80" },
  { slug: "wordpress-compress-images-before-upload", title: "WordPress Image Optimization: Why You Should Compress Before Upload (2026 Guide)", description: "Stop paying for ShortPixel, Imagify, or Smush credits. Compress and convert images BEFORE uploading to WordPress — free, no plugin needed. Tutorial with benchmark data.", date: "2026-04-08", tags: ["Performance"], coverImage: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80" },
  { slug: "passport-photo-at-home-free", title: "How to Create a Passport Photo at Home for Free (140+ Countries)", description: "Step-by-step guide to taking a compliant passport photo with your phone. AI background removal, exact dimensions for 140+ countries, free browser-based tool.", date: "2026-04-07", tags: ["Tools"], coverImage: "https://images.unsplash.com/photo-1452421822248-d4c2b47f0c81?w=800&q=80" },
  { slug: "which-apps-strip-photo-metadata", title: "Does Instagram, Telegram & Signal Strip EXIF? 12 Apps Tested [2026]", description: "Does Instagram strip EXIF metadata? Does Telegram remove GPS? Does Signal hide it? We sent the same photo through 12 apps (Instagram, WhatsApp, Signal, iMessage, Reddit, Telegram) and checked the EXIF. The 4 apps secretly leaking your location.", date: "2026-04-06", tags: ["Privacy"], coverImage: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80" },
  { slug: "check-remove-exif-data-photos", title: "How to Check and Remove EXIF Data from Your Photos (2026 Guide)", description: "Your phone embeds exact GPS coordinates into every photo you take. Learn how to check if your photos contain location data, which platforms strip it, and how to remove EXIF metadata for free.", date: "2026-04-04", tags: ["Privacy"], coverImage: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&q=80" },
  { slug: "image-compression-statistics-2026", title: "67 Image Compression Stats 2026: Page Weight, 7% Conversion Loss, Format Wars", description: "67 sourced stats every web team should bookmark: average page weight (3.5MB), how 1s slower kills 7% of conversions, WebP vs AVIF adoption (it's not what you think). Every stat with its original source.", date: "2026-04-02", tags: ["Performance"], coverImage: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80" },
  { slug: "ai-alt-text-accuracy-test-2026", title: "AI Alt Text Accuracy Test 2026: Gemini vs GPT-4o vs Claude", description: "We tested 3 AI models on 200 real images across 5 categories. See which generates the most accurate, SEO-friendly, and accessible alt text, with real data and examples.", date: "2026-04-02", tags: ["SEO"], coverImage: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=800&q=80" },
  { slug: "passport-photo-requirements-2026", title: "Passport Photo Size Requirements by Country 2026: Complete Guide + Free Maker", description: "Complete passport photo requirements for 20+ countries in 2026. Exact dimensions, file size limits, background color, and head height. Free browser-based passport photo maker included.", date: "2026-04-02", tags: ["Tools"], coverImage: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800&q=80" },
  { slug: "optimize-travel-photos-sri-lanka", title: "How to Organize Travel Photos: My Sri Lanka Workflow [2026]", description: "Back from Sri Lanka with 71 unsorted photos? Here's my exact workflow: organize by destination, AI-rename for SEO, compress, WebP convert — all free in browser.", date: "2026-03-24", tags: ["Workflow"], coverImage: "https://res.cloudinary.com/do9hrcwn1/image/upload/c_limit,f_auto,q_auto,w_1200/v1/sammapix/portfolio/sri-lanka/40-sigiriya-rock-fortress-panoramic-golden-hour-sri-lanka" },
  { slug: "ai-rename-travel-photos-seo-results", title: "I Used AI to Rename 71 Photos for SEO — Here's What Happened", description: "I renamed 71 travel photos from generic IMG_3570.JPG filenames to descriptive, keyword-rich names using AI. Here are the real results and why image filenames matter for SEO.", date: "2026-03-24", tags: ["SEO"], coverImage: "https://res.cloudinary.com/do9hrcwn1/image/upload/c_limit,f_auto,q_auto,w_1200/v1/sammapix/portfolio/sri-lanka/46-kandy-sri-lanka-temple-sacred-tooth-relic-daylight" },
  { slug: "batch-rename-photos-ai", title: "Batch Rename Photos with AI: SEO-Friendly Filenames (2026)", description: "Learn how to batch rename photos with AI automatically. Transform generic image filenames like IMG_0001.jpg into SEO-friendly, descriptive names in seconds.", date: "2026-03-21", tags: ["SEO"], coverImage: "https://images.unsplash.com/photo-1542831371-29b0f74f9713?w=800&q=80" },
  { slug: "browser-based-image-tools-privacy-guide", title: "Browser-Based Image Tools: The Complete Privacy Guide (2026)", description: "Browser-based image tools process images 100% locally — no uploads, no servers, no data leaks. The definitive guide to privacy image editing.", date: "2026-03-20", tags: ["Privacy"], coverImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80" },
  { slug: "best-tinypng-alternative-2026", title: "TinyPNG Alternative: Why Photographers Switch to SammaPix (2026)", description: "TinyPNG is trusted and excellent at one thing. But if you need batch processing, browser-side privacy, format conversion, or AI renaming — SammaPix does more, free.", date: "2026-03-19", tags: ["Tools"], coverImage: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=800&q=80" },
  { slug: "ai-image-renaming-seo-guide", title: "How AI Image Renaming Boosts Your SEO (2026 Guide)", description: "Learn how AI image rename SEO techniques transform generic filenames like IMG_0001.jpg into keyword-rich names that rank in Google Image Search.", date: "2026-03-10", tags: ["SEO"], coverImage: "https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?w=800&q=80" },
  { slug: "batch-watermark-photos-free", title: "How to Batch Watermark Photos for Free (No Photoshop Needed)", description: "Learn how to batch watermark photos for free without Photoshop. Add text, logo, or QR code watermarks to hundreds of images at once.", date: "2026-01-22", tags: ["Tools"], coverImage: "/blog/covers/batch-watermark-photos-free.webp" },
  { slug: "best-image-compression-tools-2026", title: "Best Image Compression Tools 2026: 6 Tested (TinyPNG Isn't #1)", description: "We tested 6 free image compressors on real photos: SammaPix, TinyPNG, Squoosh, ImageOptim, Compressor.io, iLoveIMG. Compression %, quality, speed, privacy compared — the 3 we recommend depend on your use case.", date: "2026-01-15", tags: ["Tools"], coverImage: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80" },
  { slug: "best-image-format-for-web-2026", title: "Best Image Format for Web 2026: WebP vs AVIF vs JPEG vs PNG", description: "The definitive guide to choosing the right image format.", date: "2026-03-13", tags: ["Performance"], coverImage: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80" },
  { slug: "optimize-images-wordpress-guide", title: "How to Optimize Images for WordPress (2026 Guide)", description: "Step-by-step guide to optimize images before uploading to WordPress.", date: "2026-01-10", tags: ["Performance"], coverImage: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80" },
  { slug: "complete-guide-webp-format", title: "Complete Guide to WebP Format: Why & How to Use It", description: "Everything you need to know about WebP: file size reduction, browser compatibility, when to use it.", date: "2026-01-28", tags: ["Performance"], coverImage: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=800&q=80" },
  { slug: "compress-images-without-losing-quality", title: "Compress Images Without Losing Quality: Best Methods Tested 2026", description: "The best ways to compress images without losing quality in 2026 — lossless and visually lossless methods tested on real photos. Free browser-based tools, no upload, no signup.", date: "2026-03-07", tags: ["Performance"], coverImage: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800&q=80" },
  { slug: "create-travel-photo-map", title: "How to Create an Interactive Travel Photo Map from Your iPhone Photos", description: "Learn how to create a travel photo map from iPhone photos using GPS EXIF data.", date: "2026-02-18", tags: ["Tools"], coverImage: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800&q=80" },
  { slug: "crop-photos-perfect-ratios", title: "How to Crop Photos to Perfect Ratios for Print and Social Media", description: "Learn every crop photo ratio you need: 1:1 for Instagram, 4:6 for print, 16:9 for widescreen.", date: "2026-02-20", tags: ["Tools"], coverImage: "https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=800&q=80&auto=format&fit=crop" },
  { slug: "make-images-load-faster-website", title: "How to Make Images Load Faster on Your Website (7 Proven Methods)", description: "Speed up your website with 7 image optimization techniques.", date: "2026-01-18", tags: ["Performance"], coverImage: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80" },
  { slug: "reduce-image-size-for-email", title: "How to Reduce Image Size for Email Attachments (Under 1MB Fast)", description: "Quickly reduce image file size for email attachments.", date: "2026-02-03", tags: ["Tools"], coverImage: "https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=800&q=80" },
  { slug: "cull-photos-faster-workflow", title: "How to Cull Photos 10x Faster: The Complete Workflow Guide", description: "Master the art of photo culling with keyboard-driven workflows.", date: "2026-02-10", tags: ["Workflow"], coverImage: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&q=80" },
  { slug: "film-effects-digital-photos-free", title: "How to Add Film Effects to Digital Photos for Free (No Photoshop)", description: "Recreate the look of Kodak Portra, Fuji Superia, and Ilford HP5 on your digital photos.", date: "2026-02-14", tags: ["Creative"], coverImage: "https://images.unsplash.com/photo-1495745966610-2a67f2297e5e?w=800&q=80" },
  { slug: "find-delete-duplicate-photos", title: "Find and Delete Duplicate Photos Free (No Upload Required)", description: "Find duplicate and near-duplicate photos in your library automatically.", date: "2026-03-12", tags: ["Tools"], coverImage: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&q=80" },
  { slug: "find-delete-duplicate-photos-free", title: "How to Find & Delete Duplicate Photos Free [2026 Guide]", description: "Your phone has hundreds of duplicate photos eating storage. Here's how to find and delete them in minutes — free, no app install, works in your browser.", date: "2026-04-16", tags: ["Tools"], coverImage: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&q=80" },
  { slug: "image-sizes-social-media-2026", title: "Image Sizes for Social Media 2026: Instagram, Facebook, Twitter", description: "Complete guide to image dimensions and aspect ratios for every social media platform.", date: "2026-03-01", tags: ["Performance"], coverImage: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800&q=80" },
  { slug: "iphone-heic-to-jpg-guide", title: "How to Convert iPhone HEIC Photos to JPG (Free Online)", description: "Convert HEIC photos from your iPhone to JPG format.", date: "2026-02-12", tags: ["Tools"], coverImage: "https://images.unsplash.com/photo-1556656793-08538906a9f8?w=900&q=80&auto=format&fit=crop" },
  { slug: "organize-travel-photos-by-country", title: "Organize Travel Photos by Country & Location (Using GPS)", description: "Sort your travel photos by location automatically using GPS data.", date: "2026-02-28", tags: ["Tools"], coverImage: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800&auto=format&fit=crop&q=80" },
  { slug: "remove-exif-protect-privacy", title: "How to Remove EXIF Data from Photos to Protect Your Privacy", description: "EXIF data contains GPS location, camera info, and timestamps. Learn how to strip it.", date: "2026-02-06", tags: ["Privacy"], coverImage: "https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=800&q=80" },
  { slug: "remove-gps-from-photos", title: "How to Remove GPS Location from Photos Before Posting Online (Free)", description: "Every photo contains hidden GPS coordinates. Learn why that is a privacy risk.", date: "2026-02-24", tags: ["Privacy"], coverImage: "https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=800&q=80" },
  { slug: "travel-photography-tips-beginners", title: "Travel Photography Tips for Beginners: Essential Guide", description: "Learn the fundamentals of travel photography: composition, lighting, gear, and workflow.", date: "2026-03-03", tags: ["Tools"], coverImage: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800&q=80" },
  { slug: "free-image-optimization-tools-online", title: "Free Image Optimization Tools Online (2026)", description: "The best free online image optimization tools compared.", date: "2026-03-22", tags: ["Tools"], coverImage: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80" },
  { slug: "how-to-speed-up-website-with-image-optimization", title: "How to Speed Up Your Website with Image Optimization", description: "Image optimization is the fastest way to improve your Core Web Vitals.", date: "2026-03-18", tags: ["Performance"], coverImage: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80" },
  { slug: "sammapix-vs-tinypng-benchmark-2026", title: "SammaPix vs TinyPNG: Benchmark Comparison 2026", description: "We tested SammaPix against TinyPNG across 50 real-world images.", date: "2026-03-16", tags: ["Tools"], coverImage: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80" },
];

export const ALL_CATEGORIES: PostTag[] = ["Tools", "SEO", "Performance", "Privacy", "Workflow", "Creative"];

export const TAG_GRADIENTS: Record<PostTag, string> = {
  Tools: "from-emerald-500/15 to-teal-500/15 dark:from-emerald-500/8 dark:to-teal-500/8",
  SEO: "from-violet-500/15 to-indigo-500/15 dark:from-violet-500/8 dark:to-indigo-500/8",
  Performance: "from-blue-500/15 to-cyan-500/15 dark:from-blue-500/8 dark:to-cyan-500/8",
  Privacy: "from-rose-500/15 to-pink-500/15 dark:from-rose-500/8 dark:to-pink-500/8",
  Workflow: "from-amber-500/15 to-orange-500/15 dark:from-amber-500/8 dark:to-orange-500/8",
  Creative: "from-fuchsia-500/15 to-purple-500/15 dark:from-fuchsia-500/8 dark:to-purple-500/8",
};

export const TAG_COLORS: Record<PostTag, string> = {
  Tools: "text-emerald-700 dark:text-emerald-400",
  SEO: "text-violet-700 dark:text-violet-400",
  Performance: "text-blue-700 dark:text-blue-400",
  Privacy: "text-rose-700 dark:text-rose-400",
  Workflow: "text-amber-700 dark:text-amber-400",
  Creative: "text-fuchsia-700 dark:text-fuchsia-400",
};

export function formatDate(dateStr: string): string {
  const date = new Date(dateStr);
  return date.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
}

export function calculateReadingTime(wordCount: number): number {
  return Math.max(1, Math.ceil(wordCount / 238));
}

export function getRelatedPosts(currentSlug: string, tags: PostTag[], count = 3): Post[] {
  return POSTS
    .filter((p) => p.slug !== currentSlug)
    .map((p) => ({
      post: p,
      score: p.tags.filter((t) => tags.includes(t)).length,
    }))
    .filter((x) => x.score > 0)
    .sort((a, b) => {
      if (b.score !== a.score) return b.score - a.score;
      return new Date(b.post.date).getTime() - new Date(a.post.date).getTime();
    })
    .slice(0, count)
    .map((x) => x.post);
}
