export type PostTag = "Tools" | "SEO" | "Performance" | "Privacy" | "Workflow" | "Creative";

export interface Post {
  slug: string;
  title: string;
  description: string;
  date: string;
  tags: PostTag[];
  coverImage?: string; // Phase 2: "/blog/covers/[slug].webp"
}

export const POSTS: Post[] = [
  { slug: "password-generator-online", title: "Free Password Generator Online — No Upload [2026]", description: "Generate strong random passwords in your browser. No upload, no server. crypto.getRandomValues, strength meter, custom options. Free.", date: "2026-08-04", tags: ["Tools", "Privacy"], coverImage: "/blog/covers/password-generator-online.webp" },
  { slug: "strong-password-generator", title: "Strong Password Generator — Length Wins [2026]", description: "Why password length beats complexity. Generate secure 16+ char passwords in your browser. No upload, no server. Free, instantly.", date: "2026-08-04", tags: ["Tools", "Privacy"], coverImage: "/blog/covers/strong-password-generator.webp" },
  { slug: "hash-generator-online", title: "Free Hash Generator Online — MD5, SHA-256, SHA-512 from Text or File [2026]", description: "Generate MD5, SHA-1, SHA-256, SHA-384, or SHA-512 hashes from any text or file entirely in your browser. No upload, no account. Web Crypto API runs locally. Free.", date: "2026-08-04", tags: ["Tools", "Privacy"], coverImage: "/blog/covers/hash-generator-online.webp" },
  { slug: "generate-sha256-md5-online", title: "How to Generate a SHA-256 or MD5 Checksum Online Without Uploading [2026]", description: "Generate a SHA-256 or MD5 checksum from text or a file in your browser — no upload, no server. Step-by-step: verify a download, compare checksums, understand the difference between MD5 and SHA-256. Free.", date: "2026-08-04", tags: ["Tools", "Privacy"], coverImage: "/blog/covers/generate-sha256-md5-online.webp" },
  { slug: "url-encode-decode-online", title: "URL Encode / Decode Online Free — Percent-Encoding Explained [2026]", description: "Encode or decode any URL online for free. Understand percent-encoding, reserved characters (%20 %2F %3F %26), encodeURIComponent vs encodeURI, and when to use each. 100% in your browser. No upload.", date: "2026-08-04", tags: ["Tools", "Workflow"], coverImage: "/blog/covers/url-encode-decode-online.webp" },
  { slug: "url-encoder-decoder-tool", title: "URL Encoder Decoder Tool — Encode & Decode URLs Online Without Installing Anything [2026]", description: "Encode or decode a URL online without installing any software. Step-by-step guide: encode a parameter with spaces and special characters, decode a received link, fix double encoding. 100% client-side. Free.", date: "2026-08-04", tags: ["Tools", "Workflow"], coverImage: "/blog/covers/url-encoder-decoder-tool.webp" },
  { slug: "barcode-reader-online", title: "Barcode Reader Online — Decode EAN, UPC, CODE128, QR from an Image [2026]", description: "Read and decode any barcode from a photo or screenshot entirely in your browser — EAN-13, EAN-8, UPC-A, CODE128, CODE39, ITF, QR. ZXing runs locally. No upload, no server, no signup. Free.", date: "2026-08-04", tags: ["Tools", "Workflow"], coverImage: "/blog/covers/barcode-reader-online.webp" },
  { slug: "scan-barcode-from-image", title: "How to Scan a Barcode from an Image or Photo (No Scanner App) [2026]", description: "Scan and decode a barcode from a product picture, screenshot, or photo — no scanner app, no camera, no upload. ZXing reads the image locally in your browser. EAN-13, UPC, CODE128, QR. Free, no signup.", date: "2026-08-04", tags: ["Tools", "Workflow"], coverImage: "/blog/covers/scan-barcode-from-image.webp" },
  { slug: "barcode-generator-online", title: "Free Barcode Generator Online — CODE128, EAN-13, UPC, QR [2026]", description: "Generate a barcode from any value entirely in your browser — CODE128, EAN-13, EAN-8, UPC-A, CODE39, ITF-14. Download PNG or SVG. No signup, no upload, no server. Free for commercial and retail use.", date: "2026-08-04", tags: ["Tools", "Workflow"], coverImage: "/blog/covers/barcode-generator-online.webp" },
  { slug: "create-barcode-free", title: "Create a Barcode for Free Without Signup — Browser-Based [2026]", description: "Create a barcode for free without signing up. Choose the right format, enter your value, download PNG or SVG. No upload, no server, no account. Works for inventory, retail labels, and asset tagging.", date: "2026-08-04", tags: ["Tools", "Workflow"], coverImage: "/blog/covers/create-barcode-free.webp" },
  { slug: "qr-code-reader-online", title: "QR Code Reader Online — Decode a QR Code from an Image Free [2026]", description: "Read and decode any QR code from an image or screenshot entirely in your browser — no upload, no camera required. jsQR runs locally. See the decoded URL, text, or contact details instantly. Free, no signup.", date: "2026-08-04", tags: ["Tools", "Privacy"], coverImage: "/blog/covers/qr-code-reader-online.webp" },
  { slug: "scan-qr-code-from-image", title: "How to Scan a QR Code from a Screenshot or Picture (No Camera) [2026]", description: "Scan and decode a QR code from a screenshot, picture, or photo — no camera needed, no upload. jsQR reads the image locally in your browser. Covers WhatsApp, email, PDF, and second-screen use cases. Free, no signup.", date: "2026-08-04", tags: ["Tools", "Privacy"], coverImage: "/blog/covers/scan-qr-code-from-image.webp" },
  { slug: "qr-code-generator-online", title: "Free QR Code Generator Online — No Signup, No Expiry [2026]", description: "Generate a QR code from any URL, text, Wi-Fi, email, or vCard entirely in your browser — no signup, no account, no expiry. Download PNG or SVG. Free for commercial use. 100% client-side, no upload.", date: "2026-08-04", tags: ["Tools", "Creative"], coverImage: "/blog/covers/qr-code-generator-online.webp" },
  { slug: "create-qr-code-no-signup", title: "Create a QR Code Without Signing Up — No Account, No Expiry [2026]", description: "Create a QR code without an account, email, or registration. Your data stays in your browser — no upload, no server. Download PNG or SVG. Free, no expiry. Find out why most generators require signup and why this one does not.", date: "2026-08-04", tags: ["Tools", "Creative"], coverImage: "/blog/covers/create-qr-code-no-signup.webp" },
  { slug: "extract-ipa-online", title: "Extract an IPA File Online Free (No Upload) [2026]", description: "Extract any iOS IPA file in your browser — no upload, no Xcode, no Mac required. An IPA is a ZIP archive. JSZip reads it locally: browse Payload/, Info.plist, assets, frameworks. Free, no signup.", date: "2026-08-04", tags: ["Tools"], coverImage: "/blog/covers/extract-ipa-online.webp" },
  { slug: "open-ipa-file-online", title: "How to Open an IPA File Online Without Installing Anything [2026]", description: "Open an .ipa file and browse its contents without Xcode, without a Mac, and without installing anything. An IPA is a renamed ZIP — view Info.plist, assets, frameworks right in your browser. No upload. Free.", date: "2026-08-04", tags: ["Tools", "Workflow"], coverImage: "/blog/covers/open-ipa-file-online.webp" },
  { slug: "tar-to-zip-online", title: "Convert TAR to ZIP Online Free (No Upload) [2026]", description: "Convert any .tar, .tar.gz, .tgz, .tar.bz2, or .tar.xz archive to ZIP entirely in your browser — no upload, no terminal, no 7-Zip install. libarchive.wasm extracts locally, JSZip repackages. Free, no signup.", date: "2026-08-04", tags: ["Tools"], coverImage: "/blog/covers/tar-to-zip-online.webp" },
  { slug: "convert-tar-to-zip-no-upload", title: "How to Convert TAR to ZIP Without Software (No Upload) [2026]", description: "Convert TAR, TAR.GZ, TGZ, TAR.BZ2, and TAR.XZ to ZIP in your browser without uploading the file and without installing 7-Zip or any other software. libarchive.wasm extracts locally, JSZip repackages. Free, no signup.", date: "2026-08-04", tags: ["Tools", "Workflow"], coverImage: "/blog/covers/convert-tar-to-zip-no-upload.webp" },
  { slug: "extract-iso-online", title: "Extract an ISO File Online Free (No Upload) [2026]", description: "Extract files from any ISO disc image in your browser — no upload, no mounting, no burning. ISO9660 supported. Browse files, download individually or as ZIP. Free, no signup.", date: "2026-08-04", tags: ["Tools"], coverImage: "/blog/covers/extract-iso-online.webp" },
  { slug: "open-iso-file-online", title: "How to Open an ISO File Without Burning or Mounting [2026]", description: "Open an .iso file and access the files inside without burning a disc or mounting a virtual drive. ISO9660 read entirely in your browser — no upload, no install, no Daemon Tools. Free.", date: "2026-08-04", tags: ["Tools", "Workflow"], coverImage: "/blog/covers/open-iso-file-online.webp" },
  { slug: "extract-apk-online", title: "Extract an APK File Online Free (No Upload) [2026]", description: "Extract any APK or XAPK file in your browser — no upload, no Android required. JSZip reads the ZIP-format archive locally. Browse AndroidManifest.xml, classes.dex, res/, assets/. Free, no signup.", date: "2026-08-04", tags: ["Tools"], coverImage: "/blog/covers/extract-apk-online.webp" },
  { slug: "open-apk-file-online", title: "How to Open an APK File Without Installing It [2026]", description: "An APK is a ZIP archive — open it in your browser to view AndroidManifest.xml, resources, and assets without installing the app. JSZip runs locally, no upload. Honest: extracts files, does not decompile bytecode. Free.", date: "2026-08-04", tags: ["Workflow"], coverImage: "/blog/covers/open-apk-file-online.webp" },
  { slug: "extract-mcpack-online", title: "Open and Extract a .mcpack File Online Free [2026]", description: "Extract any .mcpack file in your browser — no upload, no Minecraft required. JSZip reads the ZIP-format archive locally. Browse textures, manifests, and assets. Free, no signup.", date: "2026-08-04", tags: ["Tools"], coverImage: "/blog/covers/extract-mcpack-online.webp" },
  { slug: "open-minecraft-mcworld-file", title: "How to Open a .mcworld File (Minecraft World) [2026]", description: "Open and extract a .mcworld file in your browser — no upload, no Minecraft required. A .mcworld is a renamed ZIP. JSZip reads it locally: browse chunks, level data, and assets. Free.", date: "2026-08-04", tags: ["Tools", "Workflow"], coverImage: "/blog/covers/open-minecraft-mcworld-file.webp" },
  { slug: "7z-to-zip-online", title: "Convert 7Z to ZIP Online Free (No Upload) [2026]", description: "Convert any 7Z archive to ZIP entirely in your browser — no upload, no 7-Zip install, no server. libarchive.wasm extracts locally, JSZip repackages. Verifiable via DevTools. Free, no signup.", date: "2026-08-04", tags: ["Tools"], coverImage: "/blog/covers/7z-to-zip-online.webp" },
  { slug: "convert-7z-to-zip-no-upload", title: "How to Convert 7Z to ZIP Without Software [2026]", description: "Convert 7Z to ZIP in your browser without uploading the file anywhere and without installing 7-Zip. libarchive.wasm extracts locally, JSZip repackages. ZIP opens natively on Windows, Mac, Linux, iOS, Android. Free, no signup.", date: "2026-08-04", tags: ["Tools", "Workflow"], coverImage: "/blog/covers/convert-7z-to-zip-no-upload.webp" },
  { slug: "rar-to-zip-online", title: "Convert RAR to ZIP Online Free (No Upload) [2026]", description: "Convert any RAR file to ZIP entirely in your browser — no upload, no WinRAR, no server. libarchive.wasm extracts locally, JSZip repackages. Verifiable via DevTools. Free, no signup.", date: "2026-08-04", tags: ["Tools"], coverImage: "/blog/covers/rar-to-zip-online.webp" },
  { slug: "convert-rar-to-zip-no-upload", title: "How to Convert RAR to ZIP Without Uploading [2026]", description: "Convert RAR to ZIP in your browser without uploading the file anywhere. libarchive.wasm extracts locally, JSZip repackages. ZIP opens natively on Windows, Mac, Linux, iOS, Android. Free, no WinRAR, no signup.", date: "2026-08-04", tags: ["Tools", "Workflow"], coverImage: "/blog/covers/convert-rar-to-zip-no-upload.webp" },
  { slug: "txt-to-pdf-online-free", title: "Convert TXT to PDF Online Free (No Upload) [2026]", description: "Convert a .txt file or pasted text to a PDF in your browser. Runs via pdf-lib locally — the file never leaves your device. Choose font, page size, and margins. Free, no signup, no upload.", date: "2026-08-03", tags: ["Tools"], coverImage: "/blog/covers/txt-to-pdf-online-free.webp" },
  { slug: "convert-text-to-pdf-no-upload", title: "How to Convert a Text File to PDF Without Uploading [2026]", description: "Convert any .txt file or pasted text to a shareable PDF in your browser — no upload, no server, no signup. Monospace Courier font preserves log and code alignment. Word wrap handles any line length. Free.", date: "2026-08-03", tags: ["Tools", "Workflow"], coverImage: "/blog/covers/convert-text-to-pdf-no-upload.webp" },
  { slug: "flatten-pdf-online-free", title: "Flatten a PDF Online Free (No Upload) [2026]", description: "Make any PDF non-editable by flattening it in your browser — no upload, no server, no signup. pdf-lib form.flatten() converts form fields into permanent, printed content. Honest about what flatten means and what it does not do. Free.", date: "2026-08-03", tags: ["Tools"], coverImage: "/blog/covers/flatten-pdf-online-free.webp" },
  { slug: "flatten-pdf-form-no-upload", title: "How to Flatten a PDF Form (No Upload) [2026]", description: "Flatten a fillable PDF form entirely in your browser — no upload, no server, no signup. pdf-lib form.flatten() locks all form fields permanently. Fields appear identical on every PDF reader. Flatten vs print-to-PDF explained. Free.", date: "2026-08-03", tags: ["Tools", "Workflow"], coverImage: "/blog/covers/flatten-pdf-form-no-upload.webp" },
  { slug: "crop-pdf-online-free", title: "Crop a PDF Online Free (Trim Margins) [2026]", description: "Crop PDF margins per side — top, right, bottom, left — entirely in your browser via pdf-lib setCropBox. Preview with pdf.js. No upload, no signup, no server. Free.", date: "2026-08-03", tags: ["Tools"], coverImage: "/blog/covers/crop-pdf-online-free.webp" },
  { slug: "crop-pdf-margins-no-upload", title: "How to Remove White Margins from a PDF (No Upload) [2026]", description: "Remove white margins from scanned PDFs or optimize for e-reader reading — entirely in your browser via pdf-lib setCropBox. Per-side crop, live pdf.js preview, no upload, no signup. Free.", date: "2026-08-03", tags: ["Tools", "Workflow"], coverImage: "/blog/covers/crop-pdf-margins-no-upload.webp" },
  { slug: "reorder-pdf-pages-online", title: "Reorder PDF Pages Online Free [2026]", description: "Rearrange, sort, and reorder PDF pages entirely in your browser — drag and drop thumbnail grid powered by pdf.js and pdf-lib. Move pages up, down, to the top, or to the bottom. No upload, no signup. Free.", date: "2026-08-03", tags: ["Tools"], coverImage: "/blog/covers/reorder-pdf-pages-online.webp" },
  { slug: "organize-pdf-pages-no-upload", title: "How to Organize PDF Pages Without Uploading [2026]", description: "Organize, move, and rearrange PDF pages entirely in your browser — drag and drop visual thumbnails, no file upload, no server. Powered by pdf.js and pdf-lib. Fix out-of-order scans, reorder contracts, move sections privately. Free.", date: "2026-08-03", tags: ["Tools", "Privacy"], coverImage: "/blog/covers/organize-pdf-pages-no-upload.webp" },
  { slug: "sign-pdf-online-free", title: "Sign a PDF Online Free (No Upload) [2026]", description: "Add a visual signature to any PDF entirely in your browser — draw it by hand on a canvas or upload a signature image. Powered by pdf-lib. No upload, no server, no signup. Honest about visual vs certified digital signatures. Free.", date: "2026-08-03", tags: ["Privacy", "Tools"], coverImage: "/blog/covers/sign-pdf-online-free.webp" },
  { slug: "add-signature-to-pdf-no-upload", title: "How to Add a Signature to a PDF Without Uploading It [2026]", description: "Insert a visual signature on a PDF entirely in your browser — draw by hand on a canvas or upload a signature image, positioned precisely on any page via pdf-lib. No upload, no server, no signup. Honest about visual vs certified digital signatures. Free.", date: "2026-08-03", tags: ["Privacy", "Tools"], coverImage: "/blog/covers/add-signature-to-pdf-no-upload.webp" },
  { slug: "add-watermark-to-pdf-online", title: "Add a Watermark to a PDF Online Free [2026]", description: "Stamp any PDF with a text watermark (CONFIDENTIAL, DRAFT, your name) or a logo image — entirely in your browser via pdf-lib. No upload, no server, no signup. Diagonal tile, opacity control, custom font size. Free.", date: "2026-08-03", tags: ["Privacy", "Tools"], coverImage: "/blog/covers/add-watermark-to-pdf-online.webp" },
  { slug: "watermark-pdf-no-upload", title: "Watermark a PDF Without Uploading It [2026]", description: "Add a CONFIDENTIAL, DRAFT, or logo watermark to a PDF entirely in your browser via pdf-lib. No file upload, no server, no signup. Diagonal tile, opacity control, text or image. Verify with DevTools. Free.", date: "2026-08-03", tags: ["Privacy", "Tools"], coverImage: "/blog/covers/watermark-pdf-no-upload.webp" },
  { slug: "delete-pages-from-pdf-online", title: "Delete Pages from a PDF Online Free [2026]", description: "Remove one page or a range of pages from any PDF — entirely in your browser via pdf.js + pdf-lib. Thumbnail preview, range selection (e.g. 2, 5-7), no upload, no signup. Free.", date: "2026-08-03", tags: ["Privacy", "Tools"], coverImage: "/blog/covers/delete-pages-from-pdf-online.webp" },
  { slug: "remove-pdf-pages-no-upload", title: "Remove Pages from a PDF Without Uploading It [2026]", description: "Delete pages from contracts, bank statements, and confidential PDFs entirely in your browser. No upload, no server, no signup. Remove blank pages, duplicate scans, or sensitive sections privately. Free.", date: "2026-08-03", tags: ["Privacy"], coverImage: "/blog/covers/remove-pdf-pages-no-upload.webp" },
  { slug: "photo-collage-maker-online", title: "Photo Collage Maker Online Free (No Upload) [2026]", description: "Combine multiple photos into one collage in your browser — no upload, no server, no signup. Choose 2, 3, 4, 6, or 9-grid layouts. Custom gap, background color, cover or contain fit. No watermark. Free.", date: "2026-08-03", tags: ["Creative", "Tools"], coverImage: "/blog/covers/photo-collage-maker-online.webp" },
  { slug: "image-grid-maker-free", title: "How to Make an Image Grid Free (2x2, 3x3, 4x6) [2026]", description: "Create a precise image grid free — 2x2, 3x3, and more — in your browser via Canvas. Custom gap, background color, cover or contain. No upload, no watermark, no signup. Free.", date: "2026-08-03", tags: ["Creative", "Tools"], coverImage: "/blog/covers/image-grid-maker-free.webp" },
  { slug: "image-to-base64-online", title: "Convert an Image to Base64 Online Free [2026]", description: "Encode any image to Base64, Data URI, CSS background-image, or HTML img src — 100% in your browser via FileReader. No upload, no server, no signup. Reverse decode included. Free.", date: "2026-08-03", tags: ["Performance", "Tools"], coverImage: "/blog/covers/image-to-base64-online.webp" },
  { slug: "base64-to-image-converter", title: "Base64 to Image: Decode & Download Free [2026]", description: "Paste any Base64 string or Data URI and decode it back to a previewable, downloadable PNG or JPG — 100% in your browser. No upload, no server, no signup. Also supports reverse encode. Free.", date: "2026-08-03", tags: ["Performance", "Workflow"], coverImage: "/blog/covers/base64-to-image-converter.webp" },
  { slug: "add-text-to-image-online", title: "Add Text to an Image Online Free [2026]", description: "Add text to any image online — entirely in your browser via Canvas. Choose font, size, color, outline, and position. Live preview. No upload, no server, no signup. Free.", date: "2026-08-03", tags: ["Creative", "Tools"], coverImage: "/blog/covers/add-text-to-image-online.webp" },
  { slug: "add-caption-to-photo-free", title: "How to Add a Caption to a Photo Free [2026]", description: "Add a caption to any photo free — entirely in your browser via Canvas. Text outline for legibility on any background. Social, meme, watermark. No upload, no signup. Free.", date: "2026-08-03", tags: ["Creative", "Tools"], coverImage: "/blog/covers/add-caption-to-photo-free.webp" },
  { slug: "crop-image-into-circle-online", title: "Crop an Image into a Circle Online Free [2026]", description: "Crop any image into a perfect circle online — entirely in your browser via Canvas. No upload, no server, no signup. Output is a transparent PNG. Batch + ZIP. Free.", date: "2026-08-03", tags: ["Creative", "Tools"], coverImage: "/blog/covers/crop-image-into-circle-online.webp" },
  { slug: "round-image-corners-free", title: "How to Round the Corners of an Image Free [2026]", description: "Add rounded corners to any image free — entirely in your browser via Canvas. No upload, no server, no signup. Output is a transparent PNG. Choose your radius. Batch + ZIP. Free.", date: "2026-08-03", tags: ["Creative", "Tools"], coverImage: "/blog/covers/round-image-corners-free.webp" },
  { slug: "add-border-to-image-online", title: "Add a Border to an Image Online Free [2026]", description: "Add a white, black, or custom-color border to any image online — entirely in your browser via Canvas. No upload, no server, no signup. Choose expand or inset, pick any color and thickness. Batch + ZIP. Free.", date: "2026-08-03", tags: ["Creative", "Tools"], coverImage: "/blog/covers/add-border-to-image-online.webp" },
  { slug: "add-frame-to-photo-free", title: "How to Add a Frame to a Photo Free (Any Color) [2026]", description: "Add a frame or border to any photo free — white for Instagram, black for print, Polaroid-style, or any custom color. No upload, no server, runs in your browser via Canvas. Batch + ZIP. Free.", date: "2026-08-03", tags: ["Creative"], coverImage: "/blog/covers/add-frame-to-photo-free.webp" },
  { slug: "flip-image-online-no-upload", title: "Flip an Image Online Without Uploading It [2026]", description: "Mirror or flip any image horizontally or vertically — entirely in your browser via Canvas. No upload, no server, no signup. Batch flip 20 photos at once and download a ZIP. Free.", date: "2026-08-03", tags: ["Tools"], coverImage: "/blog/covers/flip-image-online-no-upload.webp" },
  { slug: "mirror-photo-online-free", title: "How to Mirror a Photo Free (Horizontal & Vertical) [2026]", description: "Mirror any photo free in your browser — horizontal flip, vertical flip, or both. Fix mirrored selfies, create reflection effects, correct reversed scans. No upload, no signup, batch + ZIP. Free.", date: "2026-08-03", tags: ["Creative", "Tools"], coverImage: "/blog/covers/mirror-photo-online-free.webp" },
  { slug: "rotate-image-online-no-upload", title: "Rotate an Image Online Without Uploading It [2026]", description: "Rotate images 90, 180, or 270 degrees — or any custom angle — entirely in your browser via Canvas. No upload, no server, no signup. Batch rotate 20 photos at once and download a ZIP. Free.", date: "2026-08-03", tags: ["Tools"], coverImage: "/blog/covers/rotate-image-online-no-upload.webp" },
  { slug: "how-to-rotate-a-photo-free", title: "How to Rotate a Photo Free (Batch, Any Angle) [2026]", description: "Rotate one photo or a batch of 20 at any angle — 90, 180, 270, or a custom degree — free in your browser. No upload, no app install, no signup. Straighten scans, fix crooked horizons, correct EXIF orientation. ZIP download.", date: "2026-08-03", tags: ["Tools"], coverImage: "/blog/covers/how-to-rotate-a-photo-free.webp" },
  { slug: "password-protect-pdf-online-no-upload", title: "Password Protect a PDF Online Without Uploading It [2026]", description: "Add an open password to any PDF in your browser — no upload, no server, no signup. Encryption runs 100% client-side via @cantoo/pdf-lib. Honest about what happens if you forget the password. Free.", date: "2026-08-03", tags: ["Privacy", "Tools"], coverImage: "/blog/covers/password-protect-pdf-online-no-upload.webp" },
  { slug: "add-password-to-pdf-free", title: "How to Add a Password to a PDF Free [2026]", description: "Add a password to any PDF free, entirely in your browser. No upload to unknown sites. Explains open password vs owner password, the risk of uploading sensitive PDFs, and what happens if you forget. Free, no signup.", date: "2026-08-03", tags: ["Privacy", "Tools"], coverImage: "/blog/covers/add-password-to-pdf-free.webp" },
  { slug: "add-page-numbers-to-pdf-online", title: "How to Add Page Numbers to a PDF Online Free [2026]", description: "Add page numbers to any PDF in your browser — no upload, no server, no signup. Choose position, format (1, 1/N, Page 1 of N), font size, and start number. Text stays selectable. Free.", date: "2026-08-03", tags: ["Tools", "Workflow"], coverImage: "/blog/covers/add-page-numbers-to-pdf-online.webp" },
  { slug: "number-pdf-pages-no-upload", title: "Number PDF Pages Without Uploading (Private, Free) [2026]", description: "Add page numbers to a PDF entirely in your browser — no file upload, no server, no signup. Custom start number, multiple formats, six positions. Ideal for theses, legal briefs, and confidential reports. Free.", date: "2026-08-03", tags: ["Privacy", "Tools"], coverImage: "/blog/covers/number-pdf-pages-no-upload.webp" },
  { slug: "unlock-pdf-online-no-upload", title: "Unlock a PDF Online Without Uploading It [2026]", description: "Remove PDF restrictions (printing, copying, editing) in your browser with no file upload. Powered by pdf-lib. Honest about what it can and cannot unlock. Free, no signup.", date: "2026-08-03", tags: ["Privacy", "Tools"], coverImage: "/blog/covers/unlock-pdf-online-no-upload.webp" },
  { slug: "remove-pdf-password-restrictions", title: "How to Remove PDF Restrictions (Printing, Copying, Editing) [2026]", description: "Enable printing, copying, and editing on a restricted PDF — free, in your browser, no upload. Explains owner-password vs user-password. Cannot crack open-password encryption. Honest guide.", date: "2026-08-03", tags: ["Privacy", "Tools"], coverImage: "/blog/covers/remove-pdf-password-restrictions.webp" },
  { slug: "rotate-pdf-online-no-upload", title: "Rotate a PDF Online Without Uploading It [2026]", description: "Rotate a PDF page by page or all at once — 90, 180, or 270 degrees. Runs entirely in your browser via pdf.js + pdf-lib. The rotation is permanent and saved into the file. No upload, no signup, free.", date: "2026-08-03", tags: ["Privacy", "Tools"], coverImage: "/blog/covers/rotate-pdf-online-no-upload.webp" },
  { slug: "how-to-rotate-pdf-pages-permanently", title: "How to Rotate PDF Pages Permanently and Save [2026]", description: "Rotate a PDF and have the rotation actually stick — not flip back when you close it. The reason why Preview and Chrome rotate only temporarily, and how to save the rotation permanently into the file. Free, no upload.", date: "2026-08-03", tags: ["Tools", "Workflow"], coverImage: "/blog/covers/how-to-rotate-pdf-pages-permanently.webp" },
  { slug: "compress-pdf-online-no-upload", title: "Compress a PDF Online Without Uploading It [2026]", description: "Compress a PDF in your browser with zero upload. Runs via pdf.js + pdf-lib locally. Ideal for scanned PDFs and image-heavy files. Honest about text-only PDFs. Free, no signup.", date: "2026-08-03", tags: ["Privacy", "Tools"], coverImage: "/blog/covers/compress-pdf-online-no-upload.webp" },
  { slug: "reduce-pdf-file-size-for-email", title: "How to Reduce PDF File Size for Email [2026]", description: "PDF too big to send by email? Compress it in your browser — no upload, no signup. Works best on scanned PDFs and image-heavy files. See before/after size, then download. Free.", date: "2026-08-03", tags: ["Tools", "Performance"], coverImage: "/blog/covers/reduce-pdf-file-size-for-email.webp" },
  { slug: "apply-lut-batch-photos-free-2026", title: "How to Apply a LUT to a Batch of Photos Free [2026]", description: "Apply one .cube LUT to 50 photos at once. Free, no Lightroom needed. Compare batch workflows: SammaPix, Lightroom, Premiere, DaVinci, FFmpeg.", date: "2026-05-18", tags: ["Tools"], coverImage: "/blog/covers/apply-lut-batch-photos-free-2026.webp" },
  { slug: "extract-lut-from-photo-free-2026", title: "How to Extract a LUT from a Photo Free [2026]", description: "Turn any photo into a real 3D LUT in 30 seconds. Free, browser-based, exports .cube for Lightroom and Premiere. Step-by-step guide with examples.", date: "2026-05-18", tags: ["Tools"], coverImage: "/blog/covers/extract-lut-from-photo-free-2026.webp" },
  { slug: "does-imessage-strip-exif-metadata", title: "Does iMessage Strip EXIF Metadata? Honest 2026 Answer", description: "iMessage does NOT strip EXIF — your GPS coordinates travel with every photo. Here is the truth + the iOS toggle that fixes it in 5 seconds.", date: "2026-05-17", tags: ["Privacy"], coverImage: "/blog/covers/does-imessage-strip-exif-metadata.webp" },
  { slug: "does-reddit-strip-exif-metadata", title: "Does Reddit Strip EXIF Metadata? Honest 2026 Answer", description: "Reddit strips EXIF on most uploads — but a real HackerOne bug exposed GPS via HEIC conversion. The history, the current status, and what to do.", date: "2026-05-17", tags: ["Privacy"], coverImage: "/blog/covers/does-reddit-strip-exif-metadata.webp" },
  { slug: "does-telegram-strip-exif-metadata", title: "Does Telegram Strip EXIF Metadata? Honest 2026 Answer", description: "Telegram strips EXIF only when you compress — send as file and full GPS coordinates travel intact. The 5-second trap most users fall into, and how to avoid it.", date: "2026-05-17", tags: ["Privacy"], coverImage: "/blog/covers/does-telegram-strip-exif-metadata.webp" },
  { slug: "does-signal-strip-exif-metadata", title: "Does Signal Strip EXIF Metadata? Honest 2026 Answer", description: "Signal is the only major messaging app that strips EXIF by default — and the only one that never keeps it server-side. Here is what is true and the open bug.", date: "2026-05-17", tags: ["Privacy"], coverImage: "/blog/covers/does-signal-strip-exif-metadata.webp" },
  { slug: "does-discord-strip-exif-metadata", title: "Does Discord Strip EXIF Metadata? Honest 2026 Answer", description: "Everyone claims Discord strips EXIF — but Discord has never documented it. We mapped what 6 sources say, the file-attachment loophole, and what to do instead.", date: "2026-05-17", tags: ["Privacy"], coverImage: "/blog/covers/does-discord-strip-exif-metadata.webp" },
  { slug: "ai-photo-renamer-custom-directive", title: "AI Photo Renamer with Custom Directives: Brand-Aware, Ecommerce, Pinterest Style (2026)", description: "Most AI photo renamers generate the same generic descriptive names for everyone. Here is how custom directives let you bias the AI toward your naming style — brand-first, ecommerce, Pinterest, niche keywords.", date: "2026-04-29", tags: ["SEO"], coverImage: "/blog/covers/ai-photo-renamer-custom-directive.webp" },
  { slug: "upscale-image-ai-free-2026", title: "AI Image Upscaler Free 2026: Real Benchmark 2x vs 4x vs 8x", description: "How AI upscaling actually works in 2026, which models produce the best results, and how to upscale 2x/4x/8x for free without paying Topaz.", date: "2026-04-23", tags: ["Performance", "Tools"], coverImage: "/blog/covers/upscale-image-ai-free-2026.webp" },
  { slug: "extract-brand-colors-from-image-2026", title: "Extract Brand Colors from Any Image: Free HEX/RGB/HSL Picker [2026]", description: "How to pull exact HEX, RGB, or HSL values from any image plus build a 6-color brand palette — free, in your browser, no upload.", date: "2026-04-22", tags: ["Creative", "Workflow"], coverImage: "/blog/covers/extract-brand-colors-from-image-2026.webp" },
  { slug: "favicon-best-practices-2026", title: "Favicon Best Practices 2026: 4 Sizes + Animated Browser Support", description: "Most favicon guides list 22 sizes — you only need 4. The exact PNG/SVG/ICO setup, animated favicon browser support, dark mode, iOS, and PWA — with the 4 HTML tags to copy-paste.", date: "2026-04-22", tags: ["Performance"], coverImage: "/blog/covers/favicon-best-practices-2026.webp" },
  { slug: "merge-pdfs-privately-no-upload", title: "Merge PDFs Privately: No Upload, No Adobe [2026 Guide]", description: "Most free PDF mergers upload your files to a server. For invoices, contracts, and tax returns that is unacceptable. Here is how to merge PDFs entirely in your browser.", date: "2026-04-22", tags: ["Privacy"], coverImage: "/blog/covers/merge-pdfs-privately-no-upload.webp" },
  { slug: "gif-to-mp4-stop-using-gifs-2026", title: "GIF to MP4: Stop Using Animated GIFs in 2026", description: "Animated GIFs are 10 to 20x larger than MP4 at the same visual quality. Why MP4/WebM replaced GIF, how to convert, and where GIF still wins.", date: "2026-04-22", tags: ["Performance"], coverImage: "/blog/covers/gif-to-mp4-stop-using-gifs-2026.webp" },
  { slug: "svg-to-png-complete-guide-developers", title: "SVG to PNG: Complete Guide for Developers [2026]", description: "The developer guide to rasterizing SVG into PNG in 2026: intrinsic sizes, @2x/@3x scaling, favicon packs, transparency, and the pitfalls most tutorials skip.", date: "2026-04-22", tags: ["Performance"], coverImage: "/blog/covers/svg-to-png-complete-guide-developers.webp" },
  { slug: "png-to-jpg-vs-webp-2026", title: "PNG to JPG vs WebP: Which One Should You Actually Use in 2026", description: "Should you convert PNG to JPG or WebP? Real benchmark on 50 images plus a decision framework. WebP beats JPG in 9 out of 10 cases.", date: "2026-04-22", tags: ["Performance"], coverImage: "/blog/covers/png-to-jpg-vs-webp-2026.webp" },
  { slug: "batch-watermark-photos-free-guide", title: "How to Batch Watermark Photos Free [2026 Guide]", description: "Add watermarks to 20 photos at once — free, no Photoshop, no upload. Text or logo watermark in your browser.", date: "2026-04-18", tags: ["Tools"], coverImage: "/blog/covers/batch-watermark-photos-free-guide.webp" },
  { slug: "heic-to-webp-converter-guide", title: "HEIC to WebP Converter: Why You Should Skip JPG in 2026", description: "Converting HEIC to JPG is a mistake. HEIC to WebP preserves more quality, produces smaller files, and WebP has 97%+ browser support.", date: "2026-04-05", tags: ["Performance"], coverImage: "/blog/covers/heic-to-webp-converter-guide.webp" },
  { slug: "optimize-images-shopify-free-guide", title: "Optimize Images for Shopify: Free Guide [2026]", description: "Learn how to optimize images for Shopify in 2026. Resize, compress, and convert to WebP for free — before uploading. Exact size specs and benchmarks.", date: "2026-04-14", tags: ["Performance"], coverImage: "/blog/covers/optimize-images-shopify-free-guide.webp" },
  { slug: "webp-vs-avif-vs-jpeg-comparison", title: "AVIF vs WebP vs JPEG: Best Image Format 2026", description: "AVIF vs WebP vs JPEG compared with real benchmarks, browser support data, and an interactive tool. Find the right image format for your site in 2026.", date: "2026-04-13", tags: ["Performance"], coverImage: "/blog/covers/webp-vs-avif-vs-jpeg-comparison.webp" },
  { slug: "best-free-remove-bg-alternatives-2026", title: "Best Free Remove.bg Alternatives 2026: 7 Background Removers Tested", description: "Remove.bg charges \u20AC0.36 per image. Here are 7 free alternatives for background removal tested on real photos \u2014 product shots, portraits, and complex edges.", date: "2026-04-12", tags: ["Tools"], coverImage: "/blog/covers/best-free-remove-bg-alternatives-2026.webp" },
  { slug: "instagram-image-quality-loss-fix", title: "Why Instagram Ruins Photo Quality + 30-Second Fix [2026]", description: "Why does Instagram ruin photo quality? It compresses up to 13x. The exact settings — dimensions, format, color profile — to upload photos that look sharp. Free fix in 30 seconds.", date: "2026-04-11", tags: ["Performance"], coverImage: "/blog/covers/instagram-image-quality-loss-fix.webp" },
  { slug: "best-free-topaz-gigapixel-alternatives-2026", title: "Topaz Gigapixel Pricing 2026 vs 7 Free Alternatives (Tested)", description: "Topaz Gigapixel AI pricing 2026: $199/year for the official subscription. We tested 7 free alternatives on the same 50 photos — max scale (4x/8x), portrait quality, speed. The free winner that beat Gigapixel on faces.", date: "2026-04-10", tags: ["Tools"], coverImage: "/blog/covers/best-free-topaz-gigapixel-alternatives-2026.webp" },
  { slug: "compress-photos-indian-exam-applications", title: "How to Compress Photos for Indian Exam Applications (JEE, NEET, UPSC, SSC)", description: "Step-by-step guide to compress and resize photos for JEE, NEET, UPSC, SSC, and GATE exam forms. Exact size requirements, signature compression, and free tools that work on your phone.", date: "2026-04-09", tags: ["Tools"], coverImage: "/blog/covers/compress-photos-indian-exam-applications.webp" },
  { slug: "wordpress-compress-images-before-upload", title: "WordPress Image Optimization: Why You Should Compress Before Upload (2026 Guide)", description: "Stop paying for ShortPixel, Imagify, or Smush credits. Compress and convert images BEFORE uploading to WordPress — free, no plugin needed. Tutorial with benchmark data.", date: "2026-04-08", tags: ["Performance"], coverImage: "/blog/covers/wordpress-compress-images-before-upload.webp" },
  { slug: "passport-photo-at-home-free", title: "How to Create a Passport Photo at Home for Free (140+ Countries)", description: "Step-by-step guide to taking a compliant passport photo with your phone. AI background removal, exact dimensions for 140+ countries, free browser-based tool.", date: "2026-04-07", tags: ["Tools"], coverImage: "/blog/covers/passport-photo-at-home-free.webp" },
  { slug: "which-apps-strip-photo-metadata", title: "Does Instagram, Telegram & Signal Strip EXIF? 12 Apps Tested [2026]", description: "Does Instagram strip EXIF metadata? Does Telegram remove GPS? Does Signal hide it? We sent the same photo through 12 apps (Instagram, WhatsApp, Signal, iMessage, Reddit, Telegram) and checked the EXIF. The 4 apps secretly leaking your location.", date: "2026-04-06", tags: ["Privacy"], coverImage: "/blog/covers/which-apps-strip-photo-metadata.webp" },
  { slug: "check-remove-exif-data-photos", title: "How to Check and Remove EXIF Data from Your Photos (2026 Guide)", description: "Your phone embeds exact GPS coordinates into every photo you take. Learn how to check if your photos contain location data, which platforms strip it, and how to remove EXIF metadata for free.", date: "2026-04-04", tags: ["Privacy"], coverImage: "/blog/covers/check-remove-exif-data-photos.webp" },
  { slug: "image-compression-statistics-2026", title: "67 Image Compression Stats 2026: Page Weight, 7% Conversion Loss, Format Wars", description: "67 sourced stats every web team should bookmark: average page weight (3.5MB), how 1s slower kills 7% of conversions, WebP vs AVIF adoption (it's not what you think). Every stat with its original source.", date: "2026-04-02", tags: ["Performance"], coverImage: "/blog/covers/image-compression-statistics-2026.webp" },
  { slug: "ai-alt-text-accuracy-test-2026", title: "AI Alt Text Accuracy Test 2026: Gemini vs GPT-4o vs Claude", description: "We tested 3 AI models on 200 real images across 5 categories. See which generates the most accurate, SEO-friendly, and accessible alt text, with real data and examples.", date: "2026-04-02", tags: ["SEO"], coverImage: "/blog/covers/ai-alt-text-accuracy-test-2026.webp" },
  { slug: "passport-photo-requirements-2026", title: "Passport Photo Size Requirements by Country 2026: Complete Guide + Free Maker", description: "Complete passport photo requirements for 20+ countries in 2026. Exact dimensions, file size limits, background color, and head height. Free browser-based passport photo maker included.", date: "2026-04-02", tags: ["Tools"], coverImage: "/blog/covers/passport-photo-requirements-2026.webp" },
  { slug: "optimize-travel-photos-sri-lanka", title: "How to Organize Travel Photos: My Sri Lanka Workflow [2026]", description: "Back from Sri Lanka with 71 unsorted photos? Here's my exact workflow: organize by destination, AI-rename for SEO, compress, WebP convert — all free in browser.", date: "2026-03-24", tags: ["Workflow"], coverImage: "/blog/covers/optimize-travel-photos-sri-lanka.webp" },
  { slug: "ai-rename-travel-photos-seo-results", title: "I Used AI to Rename 71 Photos for SEO — Here's What Happened", description: "I renamed 71 travel photos from generic IMG_3570.JPG filenames to descriptive, keyword-rich names using AI. Here are the real results and why image filenames matter for SEO.", date: "2026-03-24", tags: ["SEO"], coverImage: "/blog/covers/ai-rename-travel-photos-seo-results.webp" },
  { slug: "batch-rename-photos-ai", title: "Batch Rename Photos with AI: SEO-Friendly Filenames (2026)", description: "Learn how to batch rename photos with AI automatically. Transform generic image filenames like IMG_0001.jpg into SEO-friendly, descriptive names in seconds.", date: "2026-03-21", tags: ["SEO"], coverImage: "/blog/covers/batch-rename-photos-ai.webp" },
  { slug: "browser-based-image-tools-privacy-guide", title: "Browser-Based Image Tools: The Complete Privacy Guide (2026)", description: "Browser-based image tools process images 100% locally — no uploads, no servers, no data leaks. The definitive guide to privacy image editing.", date: "2026-03-20", tags: ["Privacy"], coverImage: "/blog/covers/browser-based-image-tools-privacy-guide.webp" },
  { slug: "best-tinypng-alternative-2026", title: "TinyPNG Alternative: Why Photographers Switch to SammaPix (2026)", description: "TinyPNG is trusted and excellent at one thing. But if you need batch processing, browser-side privacy, format conversion, or AI renaming — SammaPix does more, free.", date: "2026-03-19", tags: ["Tools"], coverImage: "/blog/covers/best-tinypng-alternative-2026.webp" },
  { slug: "ai-image-renaming-seo-guide", title: "How AI Image Renaming Boosts Your SEO (2026 Guide)", description: "Learn how AI image rename SEO techniques transform generic filenames like IMG_0001.jpg into keyword-rich names that rank in Google Image Search.", date: "2026-03-10", tags: ["SEO"], coverImage: "/blog/covers/ai-image-renaming-seo-guide.webp" },
  { slug: "batch-watermark-photos-free", title: "How to Batch Watermark Photos for Free (No Photoshop Needed)", description: "Learn how to batch watermark photos for free without Photoshop. Add text, logo, or QR code watermarks to hundreds of images at once.", date: "2026-01-22", tags: ["Tools"], coverImage: "/blog/covers/batch-watermark-photos-free.webp" },
  { slug: "best-image-compression-tools-2026", title: "Best Image Compression Tools 2026: 6 Tested (TinyPNG Isn't #1)", description: "We tested 6 free image compressors on real photos: SammaPix, TinyPNG, Squoosh, ImageOptim, Compressor.io, iLoveIMG. Compression %, quality, speed, privacy compared — the 3 we recommend depend on your use case.", date: "2026-01-15", tags: ["Tools"], coverImage: "/blog/covers/best-image-compression-tools-2026.webp" },
  { slug: "best-image-format-for-web-2026", title: "Best Image Format for Web 2026: WebP vs AVIF vs JPEG vs PNG", description: "The definitive guide to choosing the right image format.", date: "2026-03-13", tags: ["Performance"], coverImage: "/blog/covers/best-image-format-for-web-2026.webp" },
  { slug: "optimize-images-wordpress-guide", title: "How to Optimize Images for WordPress (2026 Guide)", description: "Step-by-step guide to optimize images before uploading to WordPress.", date: "2026-01-10", tags: ["Performance"], coverImage: "/blog/covers/optimize-images-wordpress-guide.webp" },
  { slug: "complete-guide-webp-format", title: "Complete Guide to WebP Format: Why & How to Use It", description: "Everything you need to know about WebP: file size reduction, browser compatibility, when to use it.", date: "2026-01-28", tags: ["Performance"], coverImage: "/blog/covers/complete-guide-webp-format.webp" },
  { slug: "compress-images-without-losing-quality", title: "Compress Images Without Losing Quality: Best Methods Tested 2026", description: "The best ways to compress images without losing quality in 2026 — lossless and visually lossless methods tested on real photos. Free browser-based tools, no upload, no signup.", date: "2026-03-07", tags: ["Performance"], coverImage: "/blog/covers/compress-images-without-losing-quality.webp" },
  { slug: "create-travel-photo-map", title: "How to Create an Interactive Travel Photo Map from Your iPhone Photos", description: "Learn how to create a travel photo map from iPhone photos using GPS EXIF data.", date: "2026-02-18", tags: ["Tools"], coverImage: "/blog/covers/create-travel-photo-map.webp" },
  { slug: "crop-photos-perfect-ratios", title: "How to Crop Photos to Perfect Ratios for Print and Social Media", description: "Learn every crop photo ratio you need: 1:1 for Instagram, 4:6 for print, 16:9 for widescreen.", date: "2026-02-20", tags: ["Tools"], coverImage: "/blog/covers/crop-photos-perfect-ratios.webp" },
  { slug: "make-images-load-faster-website", title: "How to Make Images Load Faster on Your Website (7 Proven Methods)", description: "Speed up your website with 7 image optimization techniques.", date: "2026-01-18", tags: ["Performance"], coverImage: "/blog/covers/make-images-load-faster-website.webp" },
  { slug: "reduce-image-size-for-email", title: "How to Reduce Image Size for Email Attachments (Under 1MB Fast)", description: "Quickly reduce image file size for email attachments.", date: "2026-02-03", tags: ["Tools"], coverImage: "/blog/covers/reduce-image-size-for-email.webp" },
  { slug: "cull-photos-faster-workflow", title: "How to Cull Photos 10x Faster: The Complete Workflow Guide", description: "Master the art of photo culling with keyboard-driven workflows.", date: "2026-02-10", tags: ["Workflow"], coverImage: "/blog/covers/cull-photos-faster-workflow.webp" },
  { slug: "film-effects-digital-photos-free", title: "How to Add Film Effects to Digital Photos for Free (No Photoshop)", description: "Recreate the look of Kodak Portra, Fuji Superia, and Ilford HP5 on your digital photos.", date: "2026-02-14", tags: ["Creative"], coverImage: "/blog/covers/film-effects-digital-photos-free.webp" },
  { slug: "find-delete-duplicate-photos", title: "Find and Delete Duplicate Photos Free (No Upload Required)", description: "Find duplicate and near-duplicate photos in your library automatically.", date: "2026-03-12", tags: ["Tools"], coverImage: "/blog/covers/find-delete-duplicate-photos.webp" },
  { slug: "find-delete-duplicate-photos-free", title: "How to Find & Delete Duplicate Photos Free [2026 Guide]", description: "Your phone has hundreds of duplicate photos eating storage. Here's how to find and delete them in minutes — free, no app install, works in your browser.", date: "2026-04-16", tags: ["Tools"], coverImage: "/blog/covers/find-delete-duplicate-photos-free.webp" },
  { slug: "image-sizes-social-media-2026", title: "Image Sizes for Social Media 2026: Instagram, Facebook, Twitter", description: "Complete guide to image dimensions and aspect ratios for every social media platform.", date: "2026-03-01", tags: ["Performance"], coverImage: "/blog/covers/image-sizes-social-media-2026.webp" },
  { slug: "iphone-heic-to-jpg-guide", title: "How to Convert iPhone HEIC Photos to JPG (Free Online)", description: "Convert HEIC photos from your iPhone to JPG format.", date: "2026-02-12", tags: ["Tools"], coverImage: "/blog/covers/iphone-heic-to-jpg-guide.webp" },
  { slug: "organize-travel-photos-by-country", title: "Organize Travel Photos by Country & Location (Using GPS)", description: "Sort your travel photos by location automatically using GPS data.", date: "2026-02-28", tags: ["Tools"], coverImage: "/blog/covers/organize-travel-photos-by-country.webp" },
  { slug: "remove-exif-protect-privacy", title: "How to Remove EXIF Data from Photos to Protect Your Privacy", description: "EXIF data contains GPS location, camera info, and timestamps. Learn how to strip it.", date: "2026-02-06", tags: ["Privacy"], coverImage: "/blog/covers/remove-exif-protect-privacy.webp" },
  { slug: "remove-gps-from-photos", title: "How to Remove GPS Location from Photos Before Posting Online (Free)", description: "Every photo contains hidden GPS coordinates. Learn why that is a privacy risk.", date: "2026-02-24", tags: ["Privacy"], coverImage: "/blog/covers/remove-gps-from-photos.webp" },
  { slug: "travel-photography-tips-beginners", title: "Travel Photography Tips for Beginners: Essential Guide", description: "Learn the fundamentals of travel photography: composition, lighting, gear, and workflow.", date: "2026-03-03", tags: ["Tools"], coverImage: "/blog/covers/travel-photography-tips-beginners.webp" },
  { slug: "free-image-optimization-tools-online", title: "Free Image Optimization Tools Online (2026)", description: "The best free online image optimization tools compared.", date: "2026-03-22", tags: ["Tools"], coverImage: "/blog/covers/free-image-optimization-tools-online.webp" },
  { slug: "how-to-speed-up-website-with-image-optimization", title: "How to Speed Up Your Website with Image Optimization", description: "Image optimization is the fastest way to improve your Core Web Vitals.", date: "2026-03-18", tags: ["Performance"], coverImage: "/blog/covers/how-to-speed-up-website-with-image-optimization.webp" },
  { slug: "sammapix-vs-tinypng-benchmark-2026", title: "SammaPix vs TinyPNG: Benchmark Comparison 2026", description: "We tested SammaPix against TinyPNG across 50 real-world images.", date: "2026-03-16", tags: ["Tools"], coverImage: "/blog/covers/sammapix-vs-tinypng-benchmark-2026.webp" },
];

export const ALL_CATEGORIES: PostTag[] = ["Tools", "SEO", "Performance", "Privacy", "Workflow", "Creative"];

export const TAG_GRADIENTS: Record<PostTag, string> = {
  Tools: "from-emerald-500/15 to-teal-500/15 dark:from-emerald-500/8 dark:to-teal-500/8",
  SEO: "from-violet-500/15 to-indigo-500/15 dark:from-violet-500/8 dark:to-indigo-500/8",
  Performance: "from-blue-500/15 to-cyan-500/15 dark:from-blue-500/8 dark:to-cyan-500/8",
  Privacy: "from-rose-500/15 to-pink-500/15 dark:from-rose-500/8 dark:to-pink-500/8",
  Workflow: "from-amber-500/15 to-orange-500/15 dark:from-amber-500/8 dark:to-orange-500/8",
  Creative: "from-fuchsia-500/15 to-purple-500/15 dark:from-fuchsia-500/8 dark:to-purple-500/8",
};

export const TAG_COLORS: Record<PostTag, string> = {
  Tools: "text-emerald-700 dark:text-emerald-400",
  SEO: "text-violet-700 dark:text-violet-400",
  Performance: "text-blue-700 dark:text-blue-400",
  Privacy: "text-rose-700 dark:text-rose-400",
  Workflow: "text-amber-700 dark:text-amber-400",
  Creative: "text-fuchsia-700 dark:text-fuchsia-400",
};

export function formatDate(dateStr: string): string {
  const date = new Date(dateStr);
  return date.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
}

export function calculateReadingTime(wordCount: number): number {
  return Math.max(1, Math.ceil(wordCount / 238));
}

export function getRelatedPosts(currentSlug: string, tags: PostTag[], count = 3): Post[] {
  return POSTS
    .filter((p) => p.slug !== currentSlug)
    .map((p) => ({
      post: p,
      score: p.tags.filter((t) => tags.includes(t)).length,
    }))
    .filter((x) => x.score > 0)
    .sort((a, b) => {
      if (b.score !== a.score) return b.score - a.score;
      return new Date(b.post.date).getTime() - new Date(a.post.date).getTime();
    })
    .slice(0, count)
    .map((x) => x.post);
}
