export interface ToolMeta {
  id: string;
  name: string;
  shortDesc: string;
  slug: string;
  category: "optimize" | "ai" | "organize" | "edit" | "content";
  relatedTools: string[];
  relatedBlogSlugs: string[];
}

export const TOOLS: Record<string, ToolMeta> = {
  compress: {
    id: "compress",
    name: "Compress Images",
    shortDesc: "Reduce file size up to 90%",
    slug: "/tools/compress",
    category: "optimize",
    relatedTools: ["webp", "resizepack", "exif", "croproatio"],
    relatedBlogSlugs: [
      "compress-images-without-losing-quality",
      "best-image-compression-tools-2026",
    ],
  },
  webp: {
    id: "webp",
    name: "Convert to WebP",
    shortDesc: "Smaller files with modern format",
    slug: "/tools/webp",
    category: "optimize",
    relatedTools: ["compress", "resizepack", "heic", "exif"],
    relatedBlogSlugs: [
      "best-image-format-for-web-2026",
      "compress-images-without-losing-quality",
    ],
  },
  "png-to-jpg": {
    id: "png-to-jpg",
    name: "PNG to JPG",
    shortDesc: "Convert PNG to JPG, 70-90% smaller",
    slug: "/tools/png-to-jpg",
    category: "optimize",
    relatedTools: ["compress", "webp", "exif", "resizepack"],
    relatedBlogSlugs: [
      "how-to-convert-png-to-jpg-free-no-upload",
      "png-to-jpg-vs-webp-2026",
      "best-image-format-for-web-2026",
      "compress-images-without-losing-quality",
    ],
  },
  "webp-to-jpg": {
    id: "webp-to-jpg",
    name: "WebP to JPG",
    shortDesc: "Convert WebP to JPG for universal compatibility",
    slug: "/tools/webp-to-jpg",
    category: "optimize",
    relatedTools: ["webp", "png-to-jpg", "compress", "heic"],
    relatedBlogSlugs: [
      "how-to-convert-webp-to-jpg-free-no-upload",
      "png-to-jpg-vs-webp-2026",
      "best-image-format-for-web-2026",
      "compress-images-without-losing-quality",
    ],
  },
  "webp-to-png": {
    id: "webp-to-png",
    name: "WebP to PNG",
    shortDesc: "Convert WebP to PNG, transparency preserved",
    slug: "/tools/webp-to-png",
    category: "optimize",
    relatedTools: ["webp", "webp-to-jpg", "png-to-jpg", "exif"],
    relatedBlogSlugs: [
      "png-to-jpg-vs-webp-2026",
      "best-image-format-for-web-2026",
      "compress-images-without-losing-quality",
    ],
  },
  "svg-to-png": {
    id: "svg-to-png",
    name: "SVG to PNG",
    shortDesc: "Rasterize SVG vectors to PNG at any size",
    slug: "/tools/svg-to-png",
    category: "optimize",
    relatedTools: ["png-to-jpg", "compress", "webp", "remove-bg"],
    relatedBlogSlugs: [
      "svg-to-png-complete-guide-developers",
      "favicon-best-practices-2026",
      "best-image-format-for-web-2026",
    ],
  },
  "gif-to-mp4": {
    id: "gif-to-mp4",
    name: "GIF to MP4",
    shortDesc: "Convert animated GIF to MP4 — 80-90% smaller",
    slug: "/tools/gif-to-mp4",
    category: "optimize",
    relatedTools: ["compress", "webp", "resizepack", "pdf-to-image"],
    relatedBlogSlugs: [
      "gif-to-mp4-stop-using-gifs-2026",
      "best-image-format-for-web-2026",
      "compress-images-without-losing-quality",
    ],
  },
  "ico-generator": {
    id: "ico-generator",
    name: "Favicon Generator",
    shortDesc: "Multi-size favicon.ico from any image",
    slug: "/tools/ico-generator",
    category: "optimize",
    relatedTools: ["svg-to-png", "png-to-jpg", "compress", "resizepack"],
    relatedBlogSlugs: [
      "favicon-best-practices-2026",
      "svg-to-png-complete-guide-developers",
      "best-image-format-for-web-2026",
    ],
  },
  "pdf-merge": {
    id: "pdf-merge",
    name: "Merge PDF",
    shortDesc: "Combine PDFs into one, drag to reorder",
    slug: "/tools/pdf-merge",
    category: "optimize",
    relatedTools: ["jpg-to-pdf", "pdf-to-image", "compress", "blogdrop"],
    relatedBlogSlugs: [
      "merge-pdfs-privately-no-upload",
      "browser-based-image-tools-privacy-guide",
    ],
  },
  "color-picker": {
    id: "color-picker",
    name: "Color Picker",
    shortDesc: "Eyedrop HEX/RGB/HSL + auto palette",
    slug: "/tools/color-picker",
    category: "edit",
    relatedTools: ["color-match", "filmlab", "stampit", "compress"],
    relatedBlogSlugs: [
      "extract-brand-colors-from-image-2026",
    ],
  },
  "color-match": {
    id: "color-match",
    name: "LUT Generator",
    shortDesc: "Extract 3D LUT from photo, apply to batch, export .cube",
    slug: "/tools/color-match",
    category: "ai",
    relatedTools: ["filmlab", "color-picker", "stampit", "photo-enhance"],
    relatedBlogSlugs: [
      "extract-brand-colors-from-image-2026",
    ],
  },
  "photo-enhance": {
    id: "photo-enhance",
    name: "Batch Photo Enhancer",
    shortDesc: "Drop 20+ photos, AI enhances in batch, download ZIP",
    slug: "/tools/photo-enhance",
    category: "ai",
    relatedTools: ["upscale", "compress", "remove-bg", "webp"],
    relatedBlogSlugs: [
      "compress-images-without-losing-quality",
      "best-free-topaz-gigapixel-alternatives-2026",
    ],
  },
  "ai-rename": {
    id: "ai-rename",
    name: "AI Rename",
    shortDesc: "SEO-friendly filenames with AI",
    slug: "/tools/ai-rename",
    category: "ai",
    relatedTools: ["alt-text", "smartsort", "compress", "batchname"],
    relatedBlogSlugs: [
      "ai-photo-renamer-custom-directive",
      "ai-image-renaming-seo-guide",
      "batch-rename-photos-ai",
    ],
  },
  "alt-text": {
    id: "alt-text",
    name: "AI Alt Text",
    shortDesc: "Generate accessible alt text with AI",
    slug: "/tools/alt-text",
    category: "ai",
    relatedTools: ["ai-rename", "compress", "webp", "blogdrop"],
    relatedBlogSlugs: [
      "ai-image-renaming-seo-guide",
      "image-seo-best-practices",
    ],
  },
  resizepack: {
    id: "resizepack",
    name: "Batch Resize",
    shortDesc: "Resize for social media & web",
    slug: "/tools/resizepack",
    category: "optimize",
    relatedTools: ["croproatio", "compress", "webp", "weblift"],
    relatedBlogSlugs: [
      "resize-images-for-social-media",
      "compress-images-without-losing-quality",
    ],
  },
  geosort: {
    id: "geosort",
    name: "Sort by Location",
    shortDesc: "Organize photos by GPS data",
    slug: "/tools/geosort",
    category: "organize",
    relatedTools: ["travelmap", "smartsort", "batchname", "exif"],
    relatedBlogSlugs: [],
  },
  travelmap: {
    id: "travelmap",
    name: "Travel Map",
    shortDesc: "Plot photos on a world map",
    slug: "/tools/travelmap",
    category: "organize",
    relatedTools: ["geosort", "smartsort", "exif", "ai-rename"],
    relatedBlogSlugs: [],
  },
  twinhunt: {
    id: "twinhunt",
    name: "Duplicate Finder",
    shortDesc: "Find and remove duplicate photos",
    slug: "/tools/twinhunt",
    category: "organize",
    relatedTools: ["cull", "batchname", "smartsort", "compress"],
    relatedBlogSlugs: [],
  },
  cull: {
    id: "cull",
    name: "Photo Culler",
    shortDesc: "AI-powered photo selection",
    slug: "/tools/cull",
    category: "ai",
    relatedTools: ["twinhunt", "smartsort", "compress", "ai-rename"],
    relatedBlogSlugs: [],
  },
  batchname: {
    id: "batchname",
    name: "Batch Rename",
    shortDesc: "13 tokens, EXIF dates, find/replace, case",
    slug: "/tools/batchname",
    category: "organize",
    relatedTools: ["ai-rename", "twinhunt", "smartsort", "geosort"],
    relatedBlogSlugs: [
      "how-to-batch-rename-photos-and-files-online",
      "ai-photo-renamer-custom-directive",
      "batch-rename-photos-ai",
      "ai-image-renaming-seo-guide",
    ],
  },
  filmlab: {
    id: "filmlab",
    name: "Film Lab",
    shortDesc: "Apply film-style color grading",
    slug: "/tools/filmlab",
    category: "edit",
    relatedTools: ["color-match", "stampit", "compress", "croproatio"],
    relatedBlogSlugs: [],
  },
  stampit: {
    id: "stampit",
    name: "Watermark",
    shortDesc: "Add text or image watermarks",
    slug: "/tools/stampit",
    category: "edit",
    relatedTools: ["filmlab", "compress", "resizepack", "croproatio"],
    relatedBlogSlugs: [],
  },
  heic: {
    id: "heic",
    name: "HEIC Converter",
    shortDesc: "Convert iPhone HEIC to JPG/PNG",
    slug: "/tools/heic",
    category: "optimize",
    relatedTools: ["webp", "compress", "exif", "resizepack"],
    relatedBlogSlugs: [
      "best-image-format-for-web-2026",
    ],
  },
  exif: {
    id: "exif",
    name: "EXIF Viewer",
    shortDesc: "View and strip image metadata",
    slug: "/tools/exif",
    category: "organize",
    relatedTools: ["compress", "heic", "geosort", "ai-rename"],
    relatedBlogSlugs: [],
  },
  blogdrop: {
    id: "blogdrop",
    name: "BlogDrop",
    shortDesc: "Optimize images for blog posts",
    slug: "/tools/blogdrop",
    category: "content",
    relatedTools: ["compress", "webp", "resizepack", "alt-text"],
    relatedBlogSlugs: [
      "what-size-should-blog-images-be",
      "compress-images-without-losing-quality",
    ],
  },
  transcribe: {
    id: "transcribe",
    name: "Transcribe",
    shortDesc: "Transcribe video or audio to text and SRT subtitles",
    slug: "/tools/transcribe",
    category: "ai",
    relatedTools: ["image-to-text", "blogdrop", "ai-rename", "alt-text"],
    relatedBlogSlugs: ["how-to-transcribe-video-generate-subtitles-free"],
  },
  "image-to-text": {
    id: "image-to-text",
    name: "Image to Text",
    shortDesc: "Extract text from images with AI OCR",
    slug: "/tools/image-to-text",
    category: "ai",
    relatedTools: ["transcribe", "ai-rename", "alt-text", "exif"],
    relatedBlogSlugs: [],
  },
  weblift: {
    id: "weblift",
    name: "WebLift",
    shortDesc: "Full web optimization pipeline",
    slug: "/tools/weblift",
    category: "optimize",
    relatedTools: ["compress", "webp", "resizepack", "ai-rename"],
    relatedBlogSlugs: [
      "how-to-batch-prepare-images-for-website",
      "compress-images-without-losing-quality",
      "best-image-format-for-web-2026",
    ],
  },
  smartsort: {
    id: "smartsort",
    name: "Smart Sort",
    shortDesc: "AI-powered photo organization",
    slug: "/tools/smartsort",
    category: "ai",
    relatedTools: ["ai-rename", "geosort", "cull", "batchname"],
    relatedBlogSlugs: ["how-to-organize-photos-by-category-with-ai"],
  },
  croproatio: {
    id: "croproatio",
    name: "Crop to Ratio",
    shortDesc: "Crop images to exact aspect ratios",
    slug: "/tools/croproatio",
    category: "edit",
    relatedTools: ["resizepack", "compress", "webp", "filmlab"],
    relatedBlogSlugs: [
      "resize-images-for-social-media",
    ],
  },
  "ai-organize": {
    id: "ai-organize",
    name: "AI Organize",
    shortDesc: "Auto-sort photos into folders",
    slug: "/tools/ai-organize",
    category: "ai",
    relatedTools: ["smartsort", "geosort", "batchname", "cull"],
    relatedBlogSlugs: [],
  },
  "pdf-to-image": {
    id: "pdf-to-image",
    name: "PDF to Image",
    shortDesc: "Convert PDF pages to images",
    slug: "/tools/pdf-to-image",
    category: "optimize",
    relatedTools: ["compress", "webp", "resizepack", "blogdrop"],
    relatedBlogSlugs: [],
  },
  "remove-bg": {
    id: "remove-bg",
    name: "Clean Background",
    shortDesc: "Remove image background instantly",
    slug: "/tools/remove-bg",
    category: "edit",
    relatedTools: ["compress", "croproatio", "stampit", "webp"],
    relatedBlogSlugs: [],
  },
  upscale: {
    id: "upscale",
    name: "Enhance Resolution",
    shortDesc: "AI upscale images 2x or 4x",
    slug: "/tools/upscale",
    category: "optimize",
    relatedTools: ["compress", "remove-bg", "croproatio", "webp"],
    relatedBlogSlugs: [],
  },
  "passport-photo": {
    id: "passport-photo",
    name: "Passport Photo",
    shortDesc: "AI passport & visa photo maker",
    slug: "/tools/passport-photo",
    category: "ai",
    relatedTools: ["remove-bg", "croproatio", "resizepack", "compress"],
    relatedBlogSlugs: [],
  },
  "jpg-to-pdf": {
    id: "jpg-to-pdf",
    name: "JPG to PDF",
    shortDesc: "Merge images into a single PDF",
    slug: "/tools/jpg-to-pdf",
    category: "optimize",
    relatedTools: ["pdf-to-image", "compress", "resizepack", "croproatio"],
    relatedBlogSlugs: ["how-to-combine-jpg-images-into-one-pdf", "merge-pdfs-privately-no-upload"],
  },
  jxl: {
    id: "jxl",
    name: "JXL Converter",
    shortDesc: "Convert JPEG XL to/from JPG, PNG, WebP",
    slug: "/tools/jxl",
    category: "optimize",
    relatedTools: ["webp", "heic", "compress", "pdf-to-image"],
    relatedBlogSlugs: [
      "what-is-a-jxl-file-how-to-open-convert",
      "best-image-format-for-web-2026",
      "webp-vs-avif-vs-jpeg-comparison",
    ],
  },
  unrar: {
    id: "unrar",
    name: "Open RAR Online",
    shortDesc: "Extract & view RAR files in-browser, no upload",
    slug: "/tools/unrar",
    category: "optimize",
    relatedTools: ["open-7z", "pdf-merge", "exif", "compress"],
    relatedBlogSlugs: [
      "browser-based-image-tools-privacy-guide",
      "merge-pdfs-privately-no-upload",
    ],
  },
  "open-7z": {
    id: "open-7z",
    name: "Open 7z Online",
    shortDesc: "Extract & view .7z files in-browser, convert to ZIP",
    slug: "/tools/open-7z",
    category: "optimize",
    relatedTools: ["unrar", "pdf-merge", "exif", "compress"],
    relatedBlogSlugs: [
      "browser-based-image-tools-privacy-guide",
      "merge-pdfs-privately-no-upload",
    ],
  },
  "zip-creator": {
    id: "zip-creator",
    name: "Create a ZIP File",
    shortDesc: "Bundle files or a folder into one .zip, in-browser, no upload",
    slug: "/tools/zip-creator",
    category: "optimize",
    relatedTools: ["open-7z", "unrar", "compress", "pdf-merge"],
    relatedBlogSlugs: [
      "how-to-create-a-zip-file-online-no-upload",
      "browser-based-image-tools-privacy-guide",
    ],
  },
  "tar-gz": {
    id: "tar-gz",
    name: "Open tar.gz Online",
    shortDesc: "Extract & view .tar.gz / .tgz / .gz files in-browser, convert to ZIP",
    slug: "/tools/tar-gz",
    category: "optimize",
    relatedTools: ["open-7z", "unrar", "zip-creator", "compress"],
    relatedBlogSlugs: [
      "how-to-open-tar-gz-files-online-no-upload",
      "browser-based-image-tools-privacy-guide",
    ],
  },
  "raw-converter": {
    id: "raw-converter",
    name: "RAW Converter",
    shortDesc: "Convert camera RAW (CR2, NEF, ARW, DNG) to JPG or WebP in-browser",
    slug: "/tools/raw-converter",
    category: "optimize",
    relatedTools: ["compress", "webp", "heic", "exif"],
    relatedBlogSlugs: [
      "browser-based-image-tools-privacy-guide",
    ],
  },
  "pdf-split": {
    id: "pdf-split",
    name: "Split PDF",
    shortDesc: "Extract pages or split a PDF into multiple files, in-browser",
    slug: "/tools/pdf-split",
    category: "optimize",
    relatedTools: ["pdf-merge", "jpg-to-pdf", "pdf-to-image", "compress"],
    relatedBlogSlugs: [
      "merge-pdfs-privately-no-upload",
      "browser-based-image-tools-privacy-guide",
    ],
  },
  "pdf-compress": {
    id: "pdf-compress",
    name: "Compress PDF",
    shortDesc: "Reduce PDF file size in-browser, no upload",
    slug: "/tools/pdf-compress",
    category: "optimize",
    relatedTools: ["pdf-split", "pdf-merge", "compress"],
    relatedBlogSlugs: [
      "compress-pdf-online-no-upload",
      "reduce-pdf-file-size-for-email",
    ],
  },
  "pdf-rotate": {
    id: "pdf-rotate",
    name: "Rotate PDF",
    shortDesc: "Rotate PDF pages in-browser — text stays selectable",
    slug: "/tools/pdf-rotate",
    category: "optimize",
    relatedTools: ["pdf-split", "pdf-merge", "pdf-compress"],
    relatedBlogSlugs: [
      "rotate-pdf-online-no-upload",
      "how-to-rotate-pdf-pages-permanently",
    ],
  },
  "blur-censor": {
    id: "blur-censor",
    name: "Blur & Censor",
    shortDesc: "Blur, pixelate or block faces, plates and sensitive data in a photo",
    slug: "/tools/blur-censor",
    category: "edit",
    relatedTools: ["exif", "stampit", "compress", "resizepack"],
    relatedBlogSlugs: [
      "browser-based-image-tools-privacy-guide",
    ],
  },
  "redact-pdf": {
    id: "redact-pdf",
    name: "Redact PDF",
    shortDesc: "Permanently black out sensitive text in a PDF, in-browser",
    slug: "/tools/redact-pdf",
    category: "edit",
    relatedTools: ["pdf-split", "pdf-merge", "blur-censor", "exif"],
    relatedBlogSlugs: [
      "merge-pdfs-privately-no-upload",
    ],
  },
  "compress-video": {
    id: "compress-video",
    name: "Compress Video",
    shortDesc: "Compress MP4, MOV, WebM, MKV up to 80% in-browser via WebCodecs, no upload",
    slug: "/tools/compress-video",
    category: "optimize",
    relatedTools: ["convert-video", "gif-to-mp4", "compress", "resizepack"],
    relatedBlogSlugs: [
      "compress-video-online-no-upload",
      "browser-based-image-tools-privacy-guide",
    ],
  },
  "convert-video": {
    id: "convert-video",
    name: "Convert Video",
    shortDesc: "Convert MOV, AVI, MKV, WebM to MP4 (and back) in-browser, no upload",
    slug: "/tools/convert-video",
    category: "optimize",
    relatedTools: ["compress-video", "gif-to-mp4", "webp-to-jpg", "heic"],
    relatedBlogSlugs: [
      "how-to-convert-mov-to-mp4-no-upload",
      "browser-based-image-tools-privacy-guide",
    ],
  },
  "video-to-gif": {
    id: "video-to-gif",
    name: "Video to GIF",
    shortDesc: "Convert MP4, MOV, WebM video to an animated GIF in-browser, no upload, no watermark",
    slug: "/tools/video-to-gif",
    category: "edit",
    relatedTools: ["gif-to-mp4", "compress-video", "convert-video", "compress"],
    relatedBlogSlugs: [
      "how-to-convert-video-to-gif-no-upload",
      "gif-to-mp4-stop-using-gifs-2026",
      "browser-based-image-tools-privacy-guide",
    ],
  },
  "mute-video": {
    id: "mute-video",
    name: "Mute Video",
    shortDesc: "Remove the audio from a video in-browser, instant, no re-encode, no upload",
    slug: "/tools/mute-video",
    category: "edit",
    relatedTools: ["compress-video", "convert-video", "resize-video", "video-to-gif"],
    relatedBlogSlugs: [
      "how-to-mute-a-video-remove-audio-no-upload",
      "browser-based-image-tools-privacy-guide",
    ],
  },
  "resize-video": {
    id: "resize-video",
    name: "Resize Video",
    shortDesc: "Change a video's resolution (1080p/720p/480p/360p) in-browser, no upload",
    slug: "/tools/resize-video",
    category: "optimize",
    relatedTools: ["compress-video", "convert-video", "mute-video", "resizepack"],
    relatedBlogSlugs: [
      "how-to-resize-a-video-change-resolution-no-upload",
      "browser-based-image-tools-privacy-guide",
    ],
  },
  "trim-video": {
    id: "trim-video",
    name: "Trim Video",
    shortDesc: "Cut a clip from a video (set start/end with live preview) in-browser, no upload",
    slug: "/tools/trim-video",
    category: "edit",
    relatedTools: ["compress-video", "convert-video", "video-to-gif", "mute-video"],
    relatedBlogSlugs: [
      "how-to-trim-a-video-cut-a-clip-no-upload",
      "browser-based-image-tools-privacy-guide",
    ],
  },
  "extract-audio": {
    id: "extract-audio",
    name: "Extract Audio",
    shortDesc: "Extract audio from a video as MP3 or M4A in-browser, no upload, no watermark",
    slug: "/tools/extract-audio",
    category: "edit",
    relatedTools: ["convert-video", "compress-video", "mute-video", "trim-video"],
    relatedBlogSlugs: [
      "how-to-extract-audio-from-video-mp4-to-mp3",
      "browser-based-image-tools-privacy-guide",
    ],
  },
  "instagram-grid-splitter": {
    id: "instagram-grid-splitter",
    name: "Instagram Grid Splitter",
    shortDesc: "Split a photo into a puzzle grid for Instagram (3×1, 3×2, 3×3), tiles numbered in posting order",
    slug: "/tools/instagram-grid-splitter",
    category: "edit",
    relatedTools: ["croproatio", "resizepack", "compress", "stampit"],
    relatedBlogSlugs: [
      "resize-images-for-social-media",
    ],
  },
  "pdf-unlock": {
    id: "pdf-unlock",
    name: "Unlock PDF",
    shortDesc: "Remove PDF restrictions (printing, copying, editing) in-browser, no upload",
    slug: "/tools/pdf-unlock",
    category: "optimize",
    relatedTools: ["pdf-compress", "pdf-split", "pdf-merge"],
    relatedBlogSlugs: [
      "unlock-pdf-online-no-upload",
      "remove-pdf-password-restrictions",
    ],
  },
  "pdf-page-numbers": {
    id: "pdf-page-numbers",
    name: "PDF Page Numbers",
    shortDesc: "Add page numbers to a PDF in-browser — 6 positions, 3 formats, no upload",
    slug: "/tools/pdf-page-numbers",
    category: "optimize",
    relatedTools: ["pdf-compress", "pdf-rotate", "pdf-split"],
    relatedBlogSlugs: [
      "add-page-numbers-to-pdf-online",
      "number-pdf-pages-no-upload",
    ],
  },
  "pdf-protect": {
    id: "pdf-protect",
    name: "Password Protect PDF",
    shortDesc: "Add an open-password to a PDF in-browser — encrypted locally, no upload",
    slug: "/tools/pdf-protect",
    category: "optimize",
    relatedTools: ["pdf-unlock", "pdf-compress", "pdf-split"],
    relatedBlogSlugs: [
      "password-protect-pdf-online-no-upload",
      "add-password-to-pdf-free",
    ],
  },
  "pdf-watermark": {
    id: "pdf-watermark",
    name: "Watermark PDF",
    shortDesc: "Add text or image watermarks to every PDF page in-browser — opacity, rotation, tile, no upload",
    slug: "/tools/pdf-watermark",
    category: "optimize",
    relatedTools: ["pdf-page-numbers", "pdf-protect", "stampit"],
    relatedBlogSlugs: [
      "add-watermark-to-pdf-online",
      "watermark-pdf-no-upload",
    ],
  },
  "rotate-image": {
    id: "rotate-image",
    name: "Rotate Image",
    shortDesc: "Rotate photos 90°, 180° or any custom angle — batch, no upload",
    slug: "/tools/rotate-image",
    category: "edit",
    relatedTools: ["croproatio", "resizepack", "compress", "blur-censor"],
    relatedBlogSlugs: [
      "rotate-image-online-no-upload",
      "how-to-rotate-a-photo-free",
    ],
  },
  "flip-image": {
    id: "flip-image",
    name: "Flip Image",
    shortDesc: "Mirror photos horizontally or vertically — batch, no upload",
    slug: "/tools/flip-image",
    category: "edit",
    relatedTools: ["rotate-image", "croproatio", "resizepack"],
    relatedBlogSlugs: [
      "flip-image-online-no-upload",
      "mirror-photo-online-free",
    ],
  },
  "add-border": {
    id: "add-border",
    name: "Add Border to Image",
    shortDesc: "Add a colored border or frame to photos — batch, no upload",
    slug: "/tools/add-border",
    category: "edit",
    relatedTools: ["rotate-image", "flip-image", "croproatio"],
    relatedBlogSlugs: [
      "add-border-to-image-online",
      "add-frame-to-photo-free",
    ],
  },
  "round-image": {
    id: "round-image",
    name: "Round Image",
    shortDesc: "Circle crop or rounded corners — transparent PNG, batch, no upload",
    slug: "/tools/round-image",
    category: "edit",
    relatedTools: ["croproatio", "add-border", "remove-bg"],
    relatedBlogSlugs: [
      "crop-image-into-circle-online",
      "round-image-corners-free",
    ],
  },
  "add-text-to-image": {
    id: "add-text-to-image",
    name: "Add Text to Image",
    shortDesc: "Write text on any photo — font, color, outline, position. No upload",
    slug: "/tools/add-text-to-image",
    category: "edit",
    relatedTools: ["stampit", "add-border", "croproatio"],
    relatedBlogSlugs: [
      "add-text-to-image-online",
      "add-caption-to-photo-free",
    ],
  },
  "image-to-base64": {
    id: "image-to-base64",
    name: "Image to Base64",
    shortDesc: "Convert any image to a Base64 / Data URI string — or decode back. No upload",
    slug: "/tools/image-to-base64",
    category: "edit",
    relatedTools: ["svg-to-png", "ico-generator", "compress"],
    relatedBlogSlugs: [
      "image-to-base64-online",
      "base64-to-image-converter",
    ],
  },
  "collage-maker": {
    id: "collage-maker",
    name: "Photo Collage Maker",
    shortDesc: "Combine 2-9 photos into a grid collage — 8 layouts, no upload",
    slug: "/tools/collage-maker",
    category: "edit",
    relatedTools: ["instagram-grid-splitter", "add-border", "croproatio", "resizepack"],
    relatedBlogSlugs: [
      "photo-collage-maker-online",
      "image-grid-maker-free",
    ],
  },
  "remove-pdf-pages": {
    id: "remove-pdf-pages",
    name: "Delete PDF Pages",
    shortDesc: "Remove specific pages from a PDF in-browser — click thumbnails, no upload",
    slug: "/tools/remove-pdf-pages",
    category: "optimize",
    relatedTools: ["pdf-split", "pdf-rotate", "pdf-compress"],
    relatedBlogSlugs: [
      "delete-pages-from-pdf-online",
      "remove-pdf-pages-no-upload",
    ],
  },
  "pdf-organize": {
    id: "pdf-organize",
    name: "Organize PDF Pages",
    shortDesc: "Drag or arrow-button to reorder PDF pages — no upload",
    slug: "/tools/pdf-organize",
    category: "optimize",
    relatedTools: ["pdf-split", "remove-pdf-pages", "pdf-merge"],
    relatedBlogSlugs: [
      "reorder-pdf-pages-online",
      "organize-pdf-pages-no-upload",
    ],
  },
  "pdf-sign": {
    id: "pdf-sign",
    name: "Sign PDF",
    shortDesc: "Draw or upload a signature and embed it on any PDF page — no upload",
    slug: "/tools/pdf-sign",
    category: "optimize",
    relatedTools: ["pdf-protect", "pdf-watermark", "redact-pdf"],
    relatedBlogSlugs: ["sign-pdf-online-free", "add-signature-to-pdf-no-upload"],
  },
  "crop-pdf": {
    id: "crop-pdf",
    name: "Crop PDF",
    shortDesc: "Trim PDF margins in-browser — Top/Right/Bottom/Left in pt or %, no upload",
    slug: "/tools/crop-pdf",
    category: "optimize",
    relatedTools: ["croproatio", "pdf-compress", "pdf-organize"],
    relatedBlogSlugs: ["crop-pdf-online-free", "crop-pdf-margins-no-upload"],
  },
  "txt-to-pdf": {
    id: "txt-to-pdf",
    name: "TXT to PDF",
    shortDesc: "Convert .txt files to PDF in-browser — word-wrap, A4/Letter, Courier/Helvetica, no upload",
    slug: "/tools/txt-to-pdf",
    category: "optimize",
    relatedTools: ["jpg-to-pdf", "pdf-page-numbers", "pdf-compress"],
    relatedBlogSlugs: ["txt-to-pdf-online-free", "convert-text-to-pdf-no-upload"],
  },
  "minecraft-extractor": {
    id: "minecraft-extractor",
    name: "Minecraft File Extractor",
    shortDesc: "Open .mcpack / .mcworld / .mctemplate files in-browser, no upload",
    slug: "/tools/minecraft-extractor",
    category: "optimize",
    relatedTools: ["unrar", "open-7z", "rar-to-zip"],
    relatedBlogSlugs: ["extract-mcpack-online", "open-minecraft-mcworld-file"],
  },
  "apk-extractor": {
    id: "apk-extractor",
    name: "APK Extractor",
    shortDesc: "Open & extract Android APK files in-browser — view contents, no upload",
    slug: "/tools/apk-extractor",
    category: "optimize",
    relatedTools: ["unrar", "open-7z", "minecraft-extractor"],
    relatedBlogSlugs: ["extract-apk-online", "open-apk-file-online"],
  },
  "ipa-extractor": {
    id: "ipa-extractor",
    name: "IPA Extractor",
    shortDesc: "Open & extract iOS IPA files in-browser — view contents, no upload",
    slug: "/tools/ipa-extractor",
    category: "optimize",
    relatedTools: ["apk-extractor", "open-7z", "unrar"],
    relatedBlogSlugs: ["extract-ipa-online", "open-ipa-file-online"],
  },
  "iso-extractor": {
    id: "iso-extractor",
    name: "ISO Extractor",
    shortDesc: "Browse and extract files from an ISO disc image — no upload, no mount needed",
    slug: "/tools/iso-extractor",
    category: "optimize",
    relatedTools: ["open-7z", "unrar", "7z-to-zip"],
    relatedBlogSlugs: ["extract-iso-online", "open-iso-file-online"],
  },
  "rar-to-zip": {
    id: "rar-to-zip",
    name: "RAR to ZIP",
    shortDesc: "Convert RAR archives to ZIP in-browser — extract + repackage, no upload",
    slug: "/tools/rar-to-zip",
    category: "optimize",
    relatedTools: ["unrar", "open-7z", "zip-creator"],
    relatedBlogSlugs: ["rar-to-zip-online", "convert-rar-to-zip-no-upload"],
  },
  "7z-to-zip": {
    id: "7z-to-zip",
    name: "7Z to ZIP",
    shortDesc: "Convert 7Z archives to ZIP in-browser — extract + repackage, no upload",
    slug: "/tools/7z-to-zip",
    category: "optimize",
    relatedTools: ["open-7z", "unrar", "rar-to-zip"],
    relatedBlogSlugs: ["7z-to-zip-online", "convert-7z-to-zip-no-upload"],
  },
  "tar-to-zip": {
    id: "tar-to-zip",
    name: "TAR to ZIP",
    shortDesc: "Convert TAR archives (.tar, .tar.gz, .tgz, .tar.bz2, .tar.xz) to ZIP in-browser, no upload",
    slug: "/tools/tar-to-zip",
    category: "optimize",
    relatedTools: ["7z-to-zip", "rar-to-zip", "open-7z"],
    relatedBlogSlugs: ["tar-to-zip-online", "convert-tar-to-zip-no-upload"],
  },
  "flatten-pdf": {
    id: "flatten-pdf",
    name: "Flatten PDF",
    shortDesc: "Merge form fields into the page — filled values become permanent, no upload",
    slug: "/tools/flatten-pdf",
    category: "optimize",
    relatedTools: ["pdf-protect", "pdf-watermark", "pdf-compress"],
    relatedBlogSlugs: ["flatten-pdf-online-free", "flatten-pdf-form-no-upload"],
  },
};

export function getRelatedTools(toolId: string, max = 4): ToolMeta[] {
  const tool = TOOLS[toolId];
  if (!tool) return [];
  return tool.relatedTools
    .map((id) => TOOLS[id])
    .filter(Boolean)
    .slice(0, max);
}
